/** Customer Support AI agents for Agent Studio */
export const CUSTOMER_SUPPORT_AGENTS = [
  {
    name: 'Conversation Agent',
    description: 'Orchestrates multilingual support conversations with intent routing',
    type: 'support_conversation',
    agentType: 'Customer Support' as const,
    skillIds: ['skill_cs_intent', 'skill_cs_lang', 'skill_cs_faq'],
    inputSchema: { type: 'object', properties: { message: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { response: { type: 'string' }, intent: { type: 'string' } } },
    riskLevel: 'medium' as const,
    status: 'active' as const,
  },
  {
    name: 'Voice Agent',
    description: 'STT/TTS voice conversation handler',
    type: 'support_voice',
    agentType: 'Customer Support' as const,
    skillIds: ['skill_cs_voice', 'skill_cs_tts'],
    inputSchema: { type: 'object', properties: { audio: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { transcript: { type: 'string' }, response: { type: 'string' } } },
    riskLevel: 'medium' as const,
    status: 'active' as const,
  },
  {
    name: 'Escalation Agent',
    description: 'Decides when and how to escalate to human agents',
    type: 'support_escalation',
    agentType: 'Customer Support' as const,
    skillIds: ['skill_cs_escalation'],
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object', properties: { escalate: { type: 'boolean' }, reason: { type: 'string' } } },
    riskLevel: 'high' as const,
    status: 'active' as const,
  },
  {
    name: 'CRM Sync Agent',
    description: 'Syncs customer data and tickets to CRM systems',
    type: 'support_crm',
    agentType: 'Customer Support' as const,
    skillIds: ['skill_cs_crm', 'skill_cs_ticket'],
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object', properties: { externalId: { type: 'string' } } },
    riskLevel: 'high' as const,
    status: 'active' as const,
  },
];
