import type {
  AuditLog,
  Conversation,
  Customer,
  Feedback,
  Message,
  Ticket,
} from './types.js';

export const DEMO_TENANT_ID = 'tenant_acme';

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust_001',
    tenantId: DEMO_TENANT_ID,
    email: 'sarah.mueller@example.de',
    name: 'Sarah Müller',
    phone: '+49 170 1234567',
    language: 'de',
    crmExternalId: 'zendesk_sarah_mueller',
    createdAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'cust_002',
    tenantId: DEMO_TENANT_ID,
    email: 'james.wilson@example.com',
    name: 'James Wilson',
    language: 'en',
    crmExternalId: 'zendesk_james_wilson',
    createdAt: '2026-06-05T14:00:00Z',
  },
  {
    id: 'cust_003',
    tenantId: DEMO_TENANT_ID,
    email: 'ahmed.hassan@example.ae',
    name: 'أحمد حسن',
    phone: '+971 50 987 6543',
    language: 'ar',
    createdAt: '2026-06-10T09:00:00Z',
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_001',
    tenantId: DEMO_TENANT_ID,
    customerId: 'cust_001',
    channel: 'web',
    language: 'de',
    status: 'resolved',
    intent: 'order_status',
    confidence: 0.91,
    trustScore: 88,
    decision: 'PASS',
    creditsUsed: 12,
    summary: 'Order ORD-1042 status provided with tracking link.',
    startedAt: '2026-06-28T08:15:00Z',
    endedAt: '2026-06-28T08:22:00Z',
    lastMessageAt: '2026-06-28T08:22:00Z',
  },
  {
    id: 'conv_002',
    tenantId: DEMO_TENANT_ID,
    customerId: 'cust_002',
    channel: 'web',
    language: 'en',
    status: 'escalated',
    intent: 'refund',
    confidence: 0.42,
    trustScore: 62,
    decision: 'NEEDS_INFO',
    ticketId: 'tkt_001',
    creditsUsed: 24,
    startedAt: '2026-06-29T09:00:00Z',
    lastMessageAt: '2026-06-29T09:08:00Z',
  },
  {
    id: 'conv_003',
    tenantId: DEMO_TENANT_ID,
    customerId: 'cust_003',
    channel: 'voice',
    language: 'ar',
    status: 'active',
    intent: 'technical',
    confidence: 0.78,
    trustScore: 82,
    decision: 'PASS',
    voiceSessionId: 'voice_demo_001',
    creditsUsed: 18,
    startedAt: '2026-06-29T11:30:00Z',
    lastMessageAt: '2026-06-29T11:35:00Z',
  },
  {
    id: 'conv_004',
    tenantId: DEMO_TENANT_ID,
    customerId: 'cust_002',
    channel: 'whatsapp',
    language: 'en',
    status: 'active',
    intent: 'general',
    confidence: 0.85,
    trustScore: 86,
    creditsUsed: 6,
    startedAt: '2026-06-29T12:00:00Z',
    lastMessageAt: '2026-06-29T12:02:00Z',
  },
];

export const DEMO_MESSAGES: Record<string, Message[]> = {
  conv_001: [
    {
      id: 'msg_001a',
      conversationId: 'conv_001',
      role: 'customer',
      content: 'Wo ist meine Bestellung ORD-1042?',
      language: 'de',
      intent: 'order_status',
      confidence: 0.93,
      createdAt: '2026-06-28T08:16:00Z',
    },
    {
      id: 'msg_001b',
      conversationId: 'conv_001',
      role: 'ai',
      content: 'Ihre Bestellung ORD-1042 wurde am 25. Juni versandt. Voraussichtliche Lieferung am 28. Juni.',
      language: 'de',
      intent: 'order_status',
      confidence: 0.91,
      citations: [
        {
          id: 'ref_001',
          type: 'order',
          title: 'Order ORD-1042',
          excerpt: 'Order ORD-1042 shipped on June 25.',
          sourceId: 'src_kb',
          score: 0.95,
        },
      ],
      createdAt: '2026-06-28T08:17:00Z',
    },
  ],
  conv_002: [
    {
      id: 'msg_002a',
      conversationId: 'conv_002',
      role: 'customer',
      content: 'I need an urgent refund of $500 for order #8821. This is unacceptable!',
      language: 'en',
      intent: 'refund',
      confidence: 0.88,
      createdAt: '2026-06-29T09:01:00Z',
    },
    {
      id: 'msg_002b',
      conversationId: 'conv_002',
      role: 'ai',
      content: 'I am connecting you with a specialist who can assist further.',
      language: 'en',
      intent: 'refund',
      confidence: 0.42,
      createdAt: '2026-06-29T09:02:00Z',
    },
  ],
  conv_003: [
    {
      id: 'msg_003a',
      conversationId: 'conv_003',
      role: 'customer',
      content: 'التطبيق لا يعمل بعد التحديث',
      language: 'ar',
      intent: 'technical',
      confidence: 0.8,
      createdAt: '2026-06-29T11:32:00Z',
    },
    {
      id: 'msg_003b',
      conversationId: 'conv_003',
      role: 'ai',
      content: 'يمكنني المساعدة في حل المشكلة. ما المشكلة التي تواجهها؟',
      language: 'ar',
      intent: 'technical',
      confidence: 0.78,
      createdAt: '2026-06-29T11:33:00Z',
    },
  ],
  conv_004: [
    {
      id: 'msg_004a',
      conversationId: 'conv_004',
      role: 'customer',
      content: 'Hi, I have a question about my account settings.',
      language: 'en',
      intent: 'account',
      confidence: 0.87,
      createdAt: '2026-06-29T12:01:00Z',
    },
  ],
};

export const DEMO_TICKETS: Ticket[] = [
  {
    id: 'tkt_001',
    tenantId: DEMO_TENANT_ID,
    conversationId: 'conv_002',
    customerId: 'cust_002',
    subject: 'Escalation: refund — urgent $500',
    description: 'Customer requests urgent refund for order #8821. High emotional tone.',
    status: 'in_progress',
    priority: 'urgent',
    category: 'financial',
    assigneeId: 'agent_003',
    assigneeName: 'Maria Santos',
    slaDueAt: '2026-06-29T11:00:00Z',
    slaBreached: false,
    crmExternalId: 'zendesk_ticket_99001',
    tags: ['refund', 'escalated', 'financial'],
    createdAt: '2026-06-29T09:03:00Z',
    updatedAt: '2026-06-29T09:30:00Z',
  },
  {
    id: 'tkt_002',
    tenantId: DEMO_TENANT_ID,
    customerId: 'cust_001',
    subject: 'Return request — damaged item',
    description: 'Customer reports damaged packaging on delivery.',
    status: 'open',
    priority: 'medium',
    category: 'complaint',
    slaDueAt: '2026-06-30T09:00:00Z',
    tags: ['return', 'complaint'],
    createdAt: '2026-06-29T10:00:00Z',
    updatedAt: '2026-06-29T10:00:00Z',
  },
];

export const DEMO_FEEDBACK: Feedback[] = [
  {
    id: 'fb_001',
    conversationId: 'conv_001',
    tenantId: DEMO_TENANT_ID,
    rating: 5,
    comment: 'Schnelle und hilfreiche Antwort!',
    csat: 5,
    createdAt: '2026-06-28T08:23:00Z',
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_cs_001',
    tenantId: DEMO_TENANT_ID,
    entityType: 'conversation',
    entityId: 'conv_002',
    action: 'conversation.escalated',
    actorId: 'system',
    actorName: 'Escalation Engine',
    details: { reason: 'financial', ticketId: 'tkt_001' },
    creditsUsed: 6,
    timestamp: '2026-06-29T09:03:00Z',
  },
  {
    id: 'aud_cs_002',
    tenantId: DEMO_TENANT_ID,
    entityType: 'ticket',
    entityId: 'tkt_001',
    action: 'ticket.assigned',
    actorId: 'supervisor_001',
    actorName: 'Alex Kim',
    details: { assignee: 'Maria Santos' },
    timestamp: '2026-06-29T09:30:00Z',
  },
];
