import type { Agent, Execution, Skill, Workflow } from './types.js';

export const DEMO_TENANT_ID = 'tenant_demo';

export const DEMO_SKILLS: Skill[] = [
  {
    id: 'skill_ocr_invoice',
    name: 'Invoice OCR',
    slug: 'invoice-ocr',
    skillType: 'OCR',
    category: 'data',
    description: 'Extract structured fields from invoice PDFs and images',
    inputSchema: { type: 'object', properties: { fileName: { type: 'string' }, mimeType: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { fields: { type: 'object' }, amount: { type: 'number' } } },
    creditCost: 12,
    permissions: ['documents.read', 'wallet.deduct'],
    riskLevel: 'low',
    version: '1.2.0',
    marketplaceSkillId: 'skill_invoice_extract',
    certified: true,
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'skill_fraud_score',
    name: 'Fraud Scoring',
    slug: 'fraud-scoring',
    skillType: 'Analytics',
    category: 'decision',
    description: 'Anomaly detection and duplicate invoice scoring',
    inputSchema: { type: 'object', properties: { invoiceId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { score: { type: 'number' }, alerts: { type: 'array' } } },
    creditCost: 18,
    permissions: ['wallet.deduct'],
    riskLevel: 'high',
    version: '2.0.1',
    certified: true,
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-06-10T00:00:00Z',
  },
  {
    id: 'skill_rag_retrieval',
    name: 'Knowledge Retrieval',
    slug: 'knowledge-retrieval',
    skillType: 'Retrieval',
    category: 'reasoning',
    description: 'RAG retrieval from knowledge pipeline collections',
    inputSchema: { type: 'object', properties: { query: { type: 'string' }, collectionId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { chunks: { type: 'array' }, citations: { type: 'array' } } },
    creditCost: 8,
    permissions: ['knowledge.read', 'wallet.deduct'],
    riskLevel: 'low',
    version: '1.0.0',
    certified: true,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 'skill_decision_engine',
    name: 'Decision Engine',
    slug: 'decision-engine',
    skillType: 'Decision',
    category: 'decision',
    description: 'Structured PASS/FAIL/NEEDS_INFO decision with evidence',
    inputSchema: { type: 'object', properties: { context: { type: 'object' } } },
    outputSchema: { type: 'object', properties: { decision: { type: 'string' }, reasons: { type: 'array' } } },
    creditCost: 15,
    permissions: ['wallet.deduct'],
    riskLevel: 'medium',
    version: '1.1.0',
    certified: true,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-06-20T00:00:00Z',
  },
  {
    id: 'skill_summarize',
    name: 'Executive Summarizer',
    slug: 'executive-summarizer',
    skillType: 'Summarization',
    category: 'reasoning',
    description: 'Generate executive summaries from structured data',
    inputSchema: { type: 'object', properties: { content: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { summary: { type: 'string' } } },
    creditCost: 10,
    permissions: ['wallet.deduct'],
    riskLevel: 'low',
    version: '1.0.0',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'skill_compliance_check',
    name: 'Compliance Validator',
    slug: 'compliance-validator',
    skillType: 'Compliance',
    category: 'governance',
    description: 'Policy pack validation and regulatory citation',
    inputSchema: { type: 'object', properties: { entityId: { type: 'string' }, packId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { compliant: { type: 'boolean' }, citations: { type: 'array' } } },
    creditCost: 20,
    permissions: ['governance.read', 'wallet.deduct'],
    riskLevel: 'high',
    version: '1.3.0',
    certified: true,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-06-18T00:00:00Z',
  },
  {
    id: 'skill_notify',
    name: 'Notification Dispatch',
    slug: 'notification-dispatch',
    skillType: 'Notification',
    category: 'automation',
    description: 'Email, Slack, and webhook notifications',
    inputSchema: { type: 'object', properties: { channel: { type: 'string' }, message: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { sent: { type: 'boolean' } } },
    creditCost: 5,
    permissions: ['notifications.send', 'wallet.deduct'],
    riskLevel: 'low',
    version: '1.0.0',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'skill_support_intent',
    name: 'Support Intent Classifier',
    slug: 'support-intent',
    skillType: 'Analytics',
    category: 'decision',
    description: 'Classify support tickets by intent and urgency',
    inputSchema: { type: 'object', properties: { message: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { intent: { type: 'string' }, urgency: { type: 'string' } } },
    creditCost: 7,
    permissions: ['wallet.deduct'],
    riskLevel: 'low',
    version: '1.0.0',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-06-05T00:00:00Z',
  },
  {
    id: 'skill_procurement_score',
    name: 'Procurement Scorer',
    slug: 'procurement-scorer',
    skillType: 'Decision',
    category: 'decision',
    description: 'Score supplier offers against criteria matrix',
    inputSchema: { type: 'object', properties: { offerId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { score: { type: 'number' }, ranking: { type: 'array' } } },
    creditCost: 22,
    permissions: ['wallet.deduct'],
    riskLevel: 'medium',
    version: '1.0.0',
    certified: true,
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-06-22T00:00:00Z',
  },
  {
    id: 'skill_translation',
    name: 'Multi-language Translation',
    slug: 'translation',
    skillType: 'Translation',
    category: 'data',
    description: 'Translate content across 40+ languages',
    inputSchema: { type: 'object', properties: { text: { type: 'string' }, targetLang: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { translated: { type: 'string' } } },
    creditCost: 6,
    permissions: ['wallet.deduct'],
    riskLevel: 'low',
    version: '1.0.0',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'skill_vision_inspect',
    name: 'Document Vision Inspector',
    slug: 'vision-inspect',
    skillType: 'Vision',
    category: 'data',
    description: 'Visual inspection of documents and forms',
    inputSchema: { type: 'object', properties: { imageUrl: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { labels: { type: 'array' } } },
    creditCost: 14,
    permissions: ['documents.read', 'wallet.deduct'],
    riskLevel: 'medium',
    version: '1.0.0',
    createdAt: '2026-05-15T00:00:00Z',
    updatedAt: '2026-06-10T00:00:00Z',
  },
  {
    id: 'skill_api_bridge',
    name: 'External API Bridge',
    slug: 'api-bridge',
    skillType: 'API',
    category: 'automation',
    description: 'Call external REST APIs with schema validation',
    inputSchema: { type: 'object', properties: { endpoint: { type: 'string' }, payload: { type: 'object' } } },
    outputSchema: { type: 'object', properties: { response: { type: 'object' } } },
    creditCost: 9,
    permissions: ['api.invoke', 'wallet.deduct'],
    riskLevel: 'high',
    version: '1.0.0',
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-25T00:00:00Z',
  },
];

export const DEMO_AGENTS: Omit<Agent, 'id' | 'createdAt' | 'updatedAt' | 'currentVersion'>[] = [
  {
    name: 'Invoice Extraction Agent',
    description: 'OCR and field extraction from invoice documents with validation',
    type: 'invoice_extraction',
    agentType: 'Document',
    inputSchema: { type: 'object', properties: { fileName: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { fields: { type: 'object' } } },
    riskLevel: 'low',
    status: 'active',
    skillIds: ['skill_ocr_invoice', 'skill_summarize'],
    modelId: 'gpt-4o',
    trustScore: 92,
    tenantId: DEMO_TENANT_ID,
  },
  {
    name: 'Fraud Detection Agent',
    description: 'Duplicate detection, vendor risk, and anomaly scoring',
    type: 'fraud_detection',
    agentType: 'Finance',
    inputSchema: { type: 'object', properties: { invoiceId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { score: { type: 'number' }, decision: { type: 'string' } } },
    riskLevel: 'high',
    status: 'active',
    skillIds: ['skill_fraud_score', 'skill_decision_engine'],
    modelId: 'claude-3-5-sonnet',
    trustScore: 88,
    tenantId: DEMO_TENANT_ID,
  },
  {
    name: 'Procurement Evaluator',
    description: 'Score and rank supplier offers with explainable criteria',
    type: 'procurement_eval',
    agentType: 'Procurement',
    inputSchema: { type: 'object', properties: { eventId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { ranking: { type: 'array' } } },
    riskLevel: 'medium',
    status: 'active',
    skillIds: ['skill_procurement_score', 'skill_rag_retrieval', 'skill_decision_engine'],
    modelId: 'gpt-4o',
    trustScore: 90,
    tenantId: DEMO_TENANT_ID,
  },
  {
    name: 'Support Intent Router',
    description: 'Classify and route support tickets by intent and urgency',
    type: 'support_intent',
    agentType: 'Customer Support',
    inputSchema: { type: 'object', properties: { message: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { intent: { type: 'string' }, route: { type: 'string' } } },
    riskLevel: 'low',
    status: 'active',
    skillIds: ['skill_support_intent', 'skill_notify'],
    modelId: 'gpt-4o-mini',
    trustScore: 85,
    tenantId: DEMO_TENANT_ID,
  },
  {
    name: 'Compliance Copilot',
    description: 'Policy validation, regulatory citations, and audit artifacts',
    type: 'compliance_copilot',
    agentType: 'Compliance',
    inputSchema: { type: 'object', properties: { entityId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { compliant: { type: 'boolean' } } },
    riskLevel: 'high',
    status: 'active',
    skillIds: ['skill_compliance_check', 'skill_rag_retrieval', 'skill_summarize'],
    modelId: 'claude-3-5-sonnet',
    trustScore: 94,
    publishedVersion: 2,
    tenantId: DEMO_TENANT_ID,
  },
  {
    name: 'Research Analyst',
    description: 'Retrieve knowledge, synthesize insights, and produce reports',
    type: 'research_analyst',
    agentType: 'Research',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { report: { type: 'string' } } },
    riskLevel: 'low',
    status: 'draft',
    skillIds: ['skill_rag_retrieval', 'skill_summarize'],
    modelId: 'gpt-4o',
    tenantId: DEMO_TENANT_ID,
  },
  {
    name: 'Workflow Automation Agent',
    description: 'Trigger automations and orchestrate multi-step workflows',
    type: 'workflow_automation',
    agentType: 'Automation',
    inputSchema: { type: 'object', properties: { trigger: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { runId: { type: 'string' } } },
    riskLevel: 'medium',
    status: 'active',
    skillIds: ['skill_notify', 'skill_api_bridge'],
    modelId: 'gpt-4o',
    trustScore: 82,
    tenantId: DEMO_TENANT_ID,
  },
  {
    name: 'Document Analysis Agent',
    description: 'Vision inspection and structured analysis of complex documents',
    type: 'document_analysis',
    agentType: 'Analysis',
    inputSchema: { type: 'object', properties: { documentUrl: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { analysis: { type: 'object' } } },
    riskLevel: 'medium',
    status: 'draft',
    skillIds: ['skill_vision_inspect', 'skill_ocr_invoice', 'skill_summarize'],
    modelId: 'gpt-4o',
    tenantId: DEMO_TENANT_ID,
  },
];

export const DEMO_WORKFLOW_TEMPLATES: Omit<Workflow, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    agentId: 'agent_invoice_extraction',
    name: 'Invoice Processing Pipeline',
    description: 'OCR → validate → summarize',
    steps: [
      { stepId: 'step_1', type: 'skill', skillId: 'skill_ocr_invoice', label: 'Extract fields', nextStep: 'step_2' },
      { stepId: 'step_2', type: 'skill', skillId: 'skill_decision_engine', label: 'Validate', nextStep: 'step_3' },
      { stepId: 'step_3', type: 'skill', skillId: 'skill_summarize', label: 'Summarize' },
    ],
    status: 'active',
  },
];

export const DEMO_EXECUTIONS: Execution[] = [
  {
    id: 'exec_demo_001',
    agentId: 'agent_invoice_extraction',
    agentName: 'Invoice Extraction Agent',
    input: { fileName: 'INV-2026-0042.pdf', mimeType: 'application/pdf' },
    output: {
      decision: 'PASS',
      confidence: 0.91,
      evidence: ['skill:skill_ocr_invoice', 'vendor:Acme Corp matched'],
      reasons: ['All required fields extracted', 'Amount within tolerance'],
      structured: { amount: 4250.0, vendor: 'Acme Corp' },
    },
    steps: [
      {
        stepId: 'step_1',
        skillId: 'skill_ocr_invoice',
        name: 'Extract fields',
        input: { fileName: 'INV-2026-0042.pdf' },
        output: { amount: 4250.0, vendor: 'Acme Corp' },
        durationMs: 842,
        status: 'completed',
      },
      {
        stepId: 'step_2',
        skillId: 'skill_summarize',
        name: 'Summarize',
        input: { amount: 4250.0 },
        output: { summary: 'Invoice from Acme Corp for $4,250' },
        durationMs: 312,
        status: 'completed',
      },
    ],
    logs: [
      { id: 'log_001', executionId: 'exec_demo_001', level: 'info', message: 'Execution started', timestamp: '2026-06-28T14:02:00Z' },
      { id: 'log_002', executionId: 'exec_demo_001', stepId: 'step_1', level: 'info', message: 'OCR completed · 842ms', timestamp: '2026-06-28T14:02:01Z' },
      { id: 'log_003', executionId: 'exec_demo_001', level: 'info', message: 'Execution completed · 18 credits', timestamp: '2026-06-28T14:02:02Z' },
    ],
    status: 'completed',
    creditsUsed: 18,
    latencyMs: 1154,
    startedAt: '2026-06-28T14:02:00Z',
    completedAt: '2026-06-28T14:02:02Z',
  },
  {
    id: 'exec_demo_002',
    agentId: 'agent_fraud_detection',
    agentName: 'Fraud Detection Agent',
    input: { invoiceId: 'inv_8821' },
    output: {
      decision: 'FAIL',
      confidence: 0.87,
      evidence: ['Duplicate hash match', 'Vendor risk score: 78'],
      reasons: ['Duplicate invoice detected', 'Vendor on watchlist'],
    },
    steps: [
      {
        stepId: 'step_1',
        skillId: 'skill_fraud_score',
        name: 'Fraud scoring',
        input: { invoiceId: 'inv_8821' },
        output: { score: 0.78, alerts: ['duplicate'] },
        durationMs: 1205,
        status: 'completed',
      },
    ],
    logs: [
      { id: 'log_004', executionId: 'exec_demo_002', level: 'info', message: 'Fraud scan initiated', timestamp: '2026-06-28T11:30:00Z' },
      { id: 'log_005', executionId: 'exec_demo_002', level: 'warn', message: 'Duplicate detected', timestamp: '2026-06-28T11:30:01Z' },
    ],
    status: 'completed',
    creditsUsed: 33,
    latencyMs: 1205,
    startedAt: '2026-06-28T11:30:00Z',
    completedAt: '2026-06-28T11:30:01Z',
  },
  {
    id: 'exec_demo_003',
    agentId: 'agent_procurement_eval',
    agentName: 'Procurement Evaluator',
    input: { eventId: 'evt_q2_office_supplies' },
    output: {
      decision: 'PASS',
      confidence: 0.89,
      evidence: ['3 offers evaluated', 'Criteria matrix applied'],
      reasons: ['Supplier B ranked highest on price-quality ratio'],
    },
    steps: [
      {
        stepId: 'step_1',
        skillId: 'skill_procurement_score',
        name: 'Score offers',
        input: { eventId: 'evt_q2_office_supplies' },
        output: { score: 92, ranking: ['Supplier B', 'Supplier A'] },
        durationMs: 2100,
        status: 'completed',
      },
    ],
    logs: [
      { id: 'log_006', executionId: 'exec_demo_003', level: 'info', message: 'Evaluation started', timestamp: '2026-06-27T16:00:00Z' },
    ],
    status: 'completed',
    creditsUsed: 45,
    latencyMs: 2100,
    startedAt: '2026-06-27T16:00:00Z',
    completedAt: '2026-06-27T16:00:02Z',
  },
  {
    id: 'exec_demo_004',
    agentId: 'agent_support_intent',
    agentName: 'Support Intent Router',
    input: { message: 'My order has not arrived and I need a refund' },
    output: {
      decision: 'PASS',
      confidence: 0.93,
      evidence: ['Intent: refund_request', 'Urgency: high'],
      reasons: ['Routed to billing team with priority'],
    },
    steps: [
      {
        stepId: 'step_1',
        skillId: 'skill_support_intent',
        name: 'Classify intent',
        input: { message: 'My order has not arrived and I need a refund' },
        output: { intent: 'refund_request', urgency: 'high' },
        durationMs: 420,
        status: 'completed',
      },
    ],
    logs: [
      { id: 'log_007', executionId: 'exec_demo_004', level: 'info', message: 'Intent classified', timestamp: '2026-06-27T09:15:00Z' },
    ],
    status: 'completed',
    creditsUsed: 12,
    latencyMs: 420,
    startedAt: '2026-06-27T09:15:00Z',
    completedAt: '2026-06-27T09:15:00Z',
  },
  {
    id: 'exec_demo_005',
    agentId: 'agent_compliance_copilot',
    agentName: 'Compliance Copilot',
    input: { entityId: 'vendor_acme', packId: 'soc2_2026' },
    output: {
      decision: 'NEEDS_INFO',
      confidence: 0.62,
      evidence: ['SOC2 controls 3/5 verified'],
      reasons: ['Missing vendor security questionnaire'],
    },
    steps: [
      {
        stepId: 'step_1',
        skillId: 'skill_compliance_check',
        name: 'Compliance check',
        input: { entityId: 'vendor_acme', packId: 'soc2_2026' },
        output: { compliant: false, missing: ['security_questionnaire'] },
        durationMs: 1800,
        status: 'completed',
      },
    ],
    logs: [
      { id: 'log_008', executionId: 'exec_demo_005', level: 'info', message: 'Compliance scan started', timestamp: '2026-06-26T10:00:00Z' },
      { id: 'log_009', executionId: 'exec_demo_005', level: 'warn', message: 'Missing documentation', timestamp: '2026-06-26T10:00:02Z' },
    ],
    status: 'completed',
    creditsUsed: 48,
    latencyMs: 1800,
    startedAt: '2026-06-26T10:00:00Z',
    completedAt: '2026-06-26T10:00:02Z',
  },
];

export const AGENT_ID_MAP: Record<string, string> = {
  invoice_extraction: 'agent_invoice_extraction',
  fraud_detection: 'agent_fraud_detection',
  procurement_eval: 'agent_procurement_eval',
  support_intent: 'agent_support_intent',
  compliance_copilot: 'agent_compliance_copilot',
  research_analyst: 'agent_research_analyst',
  workflow_automation: 'agent_workflow_automation',
  document_analysis: 'agent_document_analysis',
};
