import type { PlatformModuleDef } from './types.js';

/** All 25 AI Pass Platform modules */
export const PLATFORM_MODULE_DEFS: PlatformModuleDef[] = [
  {
    id: 'workspace',
    name: 'Workspace',
    description: 'Platform home — KPIs, activity, and quick actions',
    route: '/workspace',
    legacyRoute: '/dashboard',
    icon: '◫',
    category: 'core',
    tier: 'free',
    status: 'done',
    permissions: ['workspace:read'],
    dependencies: [],
    navOrder: 0,
    showInNav: true,
  },
  {
    id: 'execution',
    name: 'Execution',
    description: 'Plan, execute, and monitor AI agent runs',
    route: '/workspace/execution',
    icon: '▶',
    category: 'ai',
    tier: 'free',
    status: 'done',
    permissions: ['agents:run'],
    dependencies: ['runtime-core', 'provider-hub', 'wallet'],
    navOrder: 1,
    showInNav: true,
  },
  {
    id: 'playground',
    name: 'AI Playground',
    description: 'Chat, model compare, prompt templates, and history',
    route: '/workspace/playground',
    icon: '✦',
    category: 'ai',
    tier: 'free',
    status: 'done',
    permissions: ['playground:use'],
    dependencies: ['provider-hub', 'membership', 'wallet'],
    navOrder: 2,
    showInNav: true,
  },
  {
    id: 'automation',
    name: 'Automation',
    description: 'Visual workflow builder with event triggers',
    route: '/workspace/automation',
    icon: '⚡',
    category: 'platform',
    tier: 'professional',
    status: 'done',
    permissions: ['workflows:run'],
    dependencies: ['automation-engine', 'livesync', 'runtime-core'],
    navOrder: 4,
    showInNav: true,
  },
  {
    id: 'skills',
    name: 'Skills',
    description: 'Browse, install, and execute marketplace skills',
    route: '/workspace/skills',
    icon: '⚙',
    category: 'marketplace',
    tier: 'free',
    status: 'done',
    permissions: ['marketplace:install'],
    dependencies: ['marketplace', 'runtime-core'],
    navOrder: 5,
    showInNav: true,
  },
  {
    id: 'monitoring',
    name: 'Monitoring',
    description: 'Runtime metrics — credits, latency, confidence, trust',
    route: '/workspace/monitoring',
    icon: '📈',
    category: 'platform',
    tier: 'professional',
    status: 'done',
    permissions: ['trust:audit'],
    dependencies: ['runtime-core', 'wallet', 'provider-hub'],
    navOrder: 6,
    showInNav: true,
  },
  {
    id: 'agents',
    name: 'Agents',
    description: 'Create, configure, and run AI agents',
    route: '/workspace/agents',
    legacyRoute: '/studio',
    icon: '🤖',
    category: 'ai',
    tier: 'professional',
    status: 'stub',
    permissions: ['agents:run', 'agents:configure'],
    dependencies: ['agent-studio', 'marketplace'],
    navOrder: 2,
    showInNav: true,
  },
  {
    id: 'workflows',
    name: 'Workflows',
    description: 'Visual workflow builder and LiveSync orchestration',
    route: '/workspace/workflows',
    legacyRoute: '/platform/livesync',
    icon: '⟳',
    category: 'platform',
    tier: 'professional',
    status: 'stub',
    permissions: ['workflows:run'],
    dependencies: ['livesync', 'builder-studio'],
    navOrder: 3,
    showInNav: true,
  },
  {
    id: 'knowledge',
    name: 'Knowledge',
    description: 'Ingest, enrich, and retrieve AI-ready knowledge',
    route: '/workspace/knowledge',
    legacyRoute: '/platform/knowledge-pipeline',
    icon: '📚',
    category: 'platform',
    tier: 'professional',
    status: 'stub',
    permissions: ['knowledge:read', 'knowledge:write'],
    dependencies: ['knowledge-pipeline', 'indexer'],
    navOrder: 4,
    showInNav: true,
  },
  {
    id: 'analysis',
    name: 'Analysis',
    description: 'Analysis Studio — usage analytics, reports, and insights',
    route: '/workspace/analysis',
    legacyRoute: '/platform/presence-audit',
    icon: '📊',
    category: 'platform',
    tier: 'professional',
    status: 'stub',
    permissions: ['trust:audit'],
    dependencies: ['presence-audit'],
    navOrder: 5,
    showInNav: true,
  },
  {
    id: 'store',
    name: 'Store',
    description: 'Discover, install, and run AI apps — central distribution layer',
    route: '/workspace/store',
    legacyRoute: '/store',
    icon: '🛒',
    category: 'marketplace',
    tier: 'free',
    status: 'done',
    permissions: ['marketplace:install'],
    dependencies: ['store-core', 'marketplace-core', 'marketplace-runtime', 'wallet'],
    navOrder: 6,
    showInNav: true,
  },
  {
    id: 'discover',
    name: 'Discover',
    description: 'Intelligent AI tool discovery, comparison, deals, and SEO rankings',
    route: '/workspace/discover',
    icon: '🔎',
    category: 'marketplace',
    tier: 'free',
    status: 'done',
    permissions: ['marketplace:install'],
    dependencies: ['discovery-hub', 'marketplace-core', 'store'],
    navOrder: 5,
    showInNav: true,
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    description: 'Developer skills registry — redirects to Store for end users',
    route: '/workspace/marketplace',
    legacyRoute: '/marketplace',
    icon: '🏪',
    category: 'marketplace',
    tier: 'free',
    status: 'done',
    permissions: ['marketplace:install'],
    dependencies: ['marketplace-core', 'marketplace-runtime', 'store-core'],
    navOrder: 6.5,
    showInNav: false,
  },
  {
    id: 'apps',
    name: 'AI Apps',
    description: 'Invoice AI, Supply Chain AI, HR AI, Customer Support AI',
    route: '/workspace/apps',
    legacyRoute: '/solutions',
    icon: '📦',
    category: 'marketplace',
    tier: 'free',
    status: 'done',
    permissions: ['workspace:read'],
    dependencies: ['store', 'solutions', 'deployment'],
    navOrder: 7,
    showInNav: true,
  },
  {
    id: 'governance',
    name: 'Governance',
    description: 'AI governance operations — inventory, policies, risk, approvals, and monitoring',
    route: '/workspace/governance',
    legacyRoute: '/platform/governance',
    icon: '🏛',
    category: 'platform',
    tier: 'enterprise',
    status: 'done',
    permissions: ['governance:admin', 'compliance:approve'],
    dependencies: ['governance', 'trust'],
    navOrder: 8,
    showInNav: true,
  },
  {
    id: 'trust',
    name: 'Trust Center',
    description: 'Validate, certify, and monitor AI systems',
    route: '/workspace/trust',
    legacyRoute: '/platform/trust',
    icon: '🛡',
    category: 'platform',
    tier: 'enterprise',
    status: 'done',
    permissions: ['trust:audit'],
    dependencies: ['trust-engine'],
    navOrder: 9,
    showInNav: true,
  },
  {
    id: 'compliance',
    name: 'Compliance',
    description: 'Compliance AI — policy enforcement, risk registry, and approvals',
    route: '/workspace/compliance',
    legacyRoute: '/platform/governance',
    icon: '⚖',
    category: 'platform',
    tier: 'enterprise',
    status: 'done',
    permissions: ['compliance:approve'],
    dependencies: ['governance'],
    navOrder: 10,
    showInNav: true,
  },
  {
    id: 'presence',
    name: 'Presence Audit',
    description: 'AI Visibility Intelligence — audit, optimize, and monitor brand presence across LLM providers',
    route: '/workspace/presence',
    legacyRoute: '/workspace/apps/presence-audit',
    icon: '👁',
    category: 'platform',
    tier: 'professional',
    status: 'done',
    permissions: ['trust:audit'],
    dependencies: ['presence-audit'],
    navOrder: 10,
    showInNav: true,
  },
  {
    id: 'wallet',
    name: 'Wallet',
    description: 'AI credits, usage tracking, and billing',
    route: '/workspace/wallet',
    legacyRoute: '/billing',
    icon: '💳',
    category: 'core',
    tier: 'free',
    status: 'done',
    permissions: ['wallet:spend'],
    dependencies: ['membership', 'wallet'],
    navOrder: 11,
    showInNav: true,
  },
  {
    id: 'settings',
    name: 'Settings',
    description: 'Account, providers, membership, team, and preferences',
    route: '/workspace/settings',
    legacyRoute: '/settings',
    icon: '⚙',
    category: 'core',
    tier: 'free',
    status: 'done',
    permissions: ['settings:admin'],
    dependencies: [],
    navOrder: 12,
    showInNav: true,
  },
  {
    id: 'admin',
    name: 'Administration',
    description: 'Tenant administration, RBAC, org structure, and system config',
    route: '/workspace/admin',
    icon: '🏛',
    category: 'core',
    tier: 'enterprise',
    status: 'stub',
    permissions: ['settings:admin'],
    dependencies: [],
    navOrder: 13,
    showInNav: true,
  },
  {
    id: 'provider-hub',
    name: 'Providers',
    description: 'Model catalog, BYOK settings, and provider health',
    route: '/workspace/providers',
    icon: '🔌',
    category: 'ai',
    tier: 'free',
    status: 'done',
    permissions: ['providers:configure'],
    dependencies: ['provider-hub', 'membership'],
    navOrder: 14,
    showInNav: false,
  },
  {
    id: 'membership',
    name: 'Membership',
    description: 'Universal AI membership — one plan, every model',
    route: '/workspace/membership',
    legacyRoute: '/billing',
    icon: '👤',
    category: 'core',
    tier: 'free',
    status: 'done',
    permissions: ['settings:admin'],
    dependencies: ['membership'],
    navOrder: 15,
    showInNav: false,
  },
  {
    id: 'requirements',
    name: 'Requirements',
    description: 'Natural language business requirements capture',
    route: '/workspace/requirements',
    legacyRoute: '/requirements',
    icon: '📝',
    category: 'core',
    tier: 'free',
    status: 'done',
    permissions: ['workspace:write'],
    dependencies: ['builder-studio'],
    navOrder: 12,
    showInNav: false,
  },
  {
    id: 'builder-studio',
    name: 'Builder Studio',
    description: 'Visual canvas for forms, workflows, and agents',
    route: '/workspace/builder',
    legacyRoute: '/studio',
    icon: '🎨',
    category: 'core',
    tier: 'professional',
    status: 'done',
    permissions: ['workspace:write'],
    dependencies: ['requirements'],
    navOrder: 13,
    showInNav: false,
  },
  {
    id: 'ide',
    name: 'AI Pass Platform',
    description: 'Monaco editor with chat, agent, and terminal',
    route: '/workspace/ide',
    legacyRoute: '/ide',
    icon: '⌨',
    category: 'core',
    tier: 'professional',
    status: 'done',
    permissions: ['workspace:write', 'agents:run'],
    dependencies: ['editor', 'agent', 'ai-core'],
    navOrder: 14,
    showInNav: false,
  },
  {
    id: 'agent-studio',
    name: 'Agent Studio',
    description: 'Low-level agent registry and execution engine',
    route: '/workspace/agents/studio',
    legacyRoute: '/platform/agent-studio',
    icon: '⚡',
    category: 'ai',
    tier: 'professional',
    status: 'done',
    permissions: ['agents:configure'],
    dependencies: ['agent-studio', 'marketplace'],
    navOrder: 15,
    showInNav: false,
  },
  {
    id: 'livesync',
    name: 'LiveSync',
    description: 'Real-time event-driven AI orchestration',
    route: '/workspace/workflows/livesync',
    legacyRoute: '/platform/livesync',
    icon: '⚡',
    category: 'platform',
    tier: 'power',
    status: 'done',
    permissions: ['workflows:run'],
    dependencies: ['livesync'],
    navOrder: 16,
    showInNav: false,
  },
  {
    id: 'mcp',
    name: 'MCP Integrations',
    description: 'Model Context Protocol server connections',
    route: '/workspace/settings/mcp',
    icon: '🔗',
    category: 'infrastructure',
    tier: 'power',
    status: 'pending',
    permissions: ['settings:admin'],
    dependencies: ['mcp'],
    navOrder: 22,
    showInNav: false,
  },
  {
    id: 'indexer',
    name: 'Codebase Indexer',
    description: 'Semantic search and codebase indexing',
    route: '/workspace/knowledge/indexer',
    icon: '🔍',
    category: 'infrastructure',
    tier: 'professional',
    status: 'pending',
    permissions: ['knowledge:read'],
    dependencies: ['indexer'],
    navOrder: 23,
    showInNav: false,
  },
  {
    id: 'deployment',
    name: 'Deployment',
    description: 'Publish solutions to web, mobile, and cloud',
    route: '/workspace/apps/deploy',
    icon: '🚀',
    category: 'infrastructure',
    tier: 'professional',
    status: 'pending',
    permissions: ['workspace:write'],
    dependencies: ['deployment'],
    navOrder: 24,
    showInNav: false,
  },
  {
    id: 'invoice-ai',
    name: 'Invoice AI',
    description: 'Finance automation, invoice lifecycle, and ERP sync',
    route: '/workspace/apps/invoice-ai',
    legacyRoute: '/platform/invoice-ai',
    icon: '🧾',
    category: 'vertical',
    tier: 'professional',
    status: 'done',
    permissions: ['workspace:read'],
    dependencies: ['verticals', 'invoice-ai', 'erp-connectors'],
    navOrder: 30,
    showInNav: false,
  },
  {
    id: 'invoice-ai-erp',
    name: 'Invoice AI — ERP Connections',
    description: 'Configure Oracle, SAP, DATEV, Dynamics, QuickBooks, Xero, and custom ERP integrations',
    route: '/workspace/apps/invoice-ai/settings/erp',
    icon: '🔌',
    category: 'vertical',
    tier: 'enterprise',
    status: 'done',
    permissions: ['settings:admin'],
    dependencies: ['invoice-ai', 'erp-connectors', 'livesync'],
    navOrder: 31,
    showInNav: false,
  },
  {
    id: 'supply-chain',
    name: 'Supply Chain AI',
    description: 'Procurement offer evaluation and ranking',
    route: '/workspace/apps/supply-chain-ai',
    legacyRoute: '/platform/supply-chain',
    icon: '📦',
    category: 'vertical',
    tier: 'professional',
    status: 'done',
    permissions: ['workspace:read'],
    dependencies: ['verticals', 'supply-chain-ai', 'agent-studio', 'livesync', 'wallet', 'membership', 'erp-connectors'],
    navOrder: 31,
    showInNav: true,
  },
  {
    id: 'customer-support',
    name: 'Customer Support AI',
    description: 'Voice + text multi-language support agent',
    route: '/workspace/apps/customer-support-ai',
    legacyRoute: '/platform/customer-support',
    icon: '💬',
    category: 'vertical',
    tier: 'professional',
    status: 'done',
    permissions: ['workspace:read'],
    dependencies: ['verticals', 'customer-support-ai', 'agent-studio', 'livesync', 'wallet', 'membership', 'marketplace', 'knowledge-pipeline', 'trust'],
    navOrder: 32,
    showInNav: false,
  },
  {
    id: 'sales-ai',
    name: 'Sales AI',
    description: 'AI-powered Revenue Operating System — email, LinkedIn, proposals, CRM, campaigns',
    route: '/workspace/apps/sales-ai',
    icon: '📈',
    category: 'vertical',
    tier: 'professional',
    status: 'done',
    permissions: ['workspace:read'],
    dependencies: ['verticals', 'sales-ai', 'agent-studio', 'livesync', 'wallet', 'membership', 'marketplace', 'knowledge-pipeline', 'trust', 'crm-connectors', 'provider-hub'],
    navOrder: 33,
    showInNav: true,
  },
  {
    id: 'compliance-ai',
    name: 'Compliance AI',
    description: 'Enterprise compliance operations — frameworks, risks, evidence, trust center',
    route: '/workspace/apps/compliance-ai',
    legacyRoute: '/workspace/compliance',
    icon: '⚖',
    category: 'vertical',
    tier: 'professional',
    status: 'done',
    permissions: ['workspace:read'],
    dependencies: ['governance', 'trust', 'livesync', 'wallet', 'membership', 'knowledge-pipeline', 'compliance-ai'],
    navOrder: 33,
    showInNav: false,
  },
];
