/** Content AI marketplace skills */
export const CONTENT_AI_SKILLS = [
  {
    id: 'skill_content_detect',
    name: 'ContentDetectSkill',
    slug: 'content-detect',
    description: 'AI-generated text detection with sentence-level probability scoring.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'analytics' as const,
    riskLevel: 'low' as const,
    planTierRequired: 'free' as const,
    inputSchema: { type: 'object', properties: { text: { type: 'string' } } },
    outputSchema: {
      type: 'object',
      properties: { aiScore: { type: 'number' }, humanScore: { type: 'number' } },
    },
    creditCost: 1,
    deterministic: false,
    explainabilityRequired: true,
    platforms: ['web'],
    tags: ['writing', 'detection', 'compliance'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet'],
    lifecycleStatus: 'published' as const,
    certified: true,
    featured: true,
    trending: true,
    installCount: 420,
    rating: 4.7,
    reviewCount: 28,
  },
  {
    id: 'skill_content_humanize',
    name: 'ContentHumanizeSkill',
    slug: 'content-humanize',
    description: 'Humanize AI-generated text with tone control and multi-model routing.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'communication' as const,
    riskLevel: 'medium' as const,
    planTierRequired: 'professional' as const,
    inputSchema: {
      type: 'object',
      properties: { text: { type: 'string' }, tone: { type: 'string' } },
    },
    outputSchema: { type: 'object', properties: { humanizedText: { type: 'string' } } },
    creditCost: 5,
    deterministic: false,
    explainabilityRequired: false,
    platforms: ['web'],
    tags: ['writing', 'humanize', 'marketing'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet', 'gemini-1.5-pro'],
    lifecycleStatus: 'published' as const,
    certified: true,
    featured: true,
    trending: true,
    installCount: 380,
    rating: 4.8,
    reviewCount: 35,
  },
];
