import type { BestAiPageContent, Collection, Comparison, DiscoveryDeal, NewsArticle, ResearchArticle } from './types.js';

export const BEST_AI_PAGES: BestAiPageContent[] = [
  {
    slug: 'finance',
    title: 'Best AI Tools for Finance',
    headline: 'Top finance automation & invoice AI tools',
    description: 'Compare certified finance apps for AP automation, fraud detection, and compliance.',
    seoTitle: 'Best AI Tools for Finance 2026 | AI Pass Discovery',
    seoDescription: 'Discover the best AI tools for finance teams — invoice automation, compliance, and fraud detection.',
    toolIds: ['app_invoice_ai', 'app_compliance_guard', 'app_legal_contract_ai'],
  },
  {
    slug: 'hr',
    title: 'Best AI Tools for HR',
    headline: 'Recruiting, screening & onboarding AI',
    description: 'HR teams use these AI tools for resume parsing, candidate screening, and onboarding.',
    seoTitle: 'Best AI Tools for HR 2026 | AI Pass Discovery',
    seoDescription: 'Top HR AI tools for recruiting, resume parsing, and employee onboarding automation.',
    toolIds: ['app_hr_ai', 'app_customer_support_ai'],
  },
  {
    slug: 'developers',
    title: 'Best AI Tools for Developers',
    headline: 'Agent skills, RAG packs & dev tooling',
    description: 'Build production AI agents with open source toolkits and knowledge pipeline packs.',
    seoTitle: 'Best AI Tools for Developers 2026 | AI Pass Discovery',
    seoDescription: 'Developer-focused AI tools — agent skills, RAG pipelines, and open source packs.',
    toolIds: ['app_agent_toolkit_oss', 'app_knowledge_pipeline_pack', 'app_iot_anomaly_detector'],
  },
  {
    slug: 'agents',
    title: 'Best AI Agent Tools',
    headline: 'Production-ready agent packs & copilots',
    description: 'Deploy AI agents for sales, support, and workflow automation.',
    seoTitle: 'Best AI Agent Tools 2026 | AI Pass Discovery',
    seoDescription: 'Compare the best AI agent tools for customer support, sales, and automation.',
    toolIds: ['app_customer_support_ai', 'app_sales_copilot', 'app_agent_toolkit_oss'],
  },
  {
    slug: 'automation',
    title: 'Best AI Automation Tools',
    headline: 'Workflow automation & decision engines',
    description: 'Automate procurement, invoicing, and compliance with certified AI packs.',
    seoTitle: 'Best AI Automation Tools 2026 | AI Pass Discovery',
    seoDescription: 'Top AI automation tools for enterprise workflows, procurement, and finance.',
    toolIds: ['app_invoice_ai', 'app_supply_chain_ai', 'app_hr_ai', 'app_compliance_guard'],
  },
  {
    slug: 'platforms',
    title: 'Best AI Platforms',
    headline: 'Enterprise AI operating systems & marketplaces',
    description: 'Full-stack AI platforms with governance, wallet, and marketplace built in.',
    seoTitle: 'Best AI Platforms 2026 | AI Pass Discovery',
    seoDescription: 'Compare enterprise AI platforms with governance, marketplace, and unified wallet.',
    toolIds: ['app_invoice_ai', 'app_compliance_guard', 'app_knowledge_pipeline_pack'],
    membershipGate: 'professional',
  },
  {
    slug: 'europe',
    title: 'Best AI Tools in Europe',
    headline: 'GDPR-ready enterprise AI for EU teams',
    description: 'Certified, enterprise-ready AI tools popular with European organizations.',
    seoTitle: 'Best AI Tools in Europe 2026 | AI Pass Discovery',
    seoDescription: 'GDPR-ready AI tools for European enterprises — compliance, finance, and support.',
    toolIds: ['app_compliance_guard', 'app_invoice_ai', 'app_legal_contract_ai'],
  },
  {
    slug: 'open-source',
    title: 'Best Open Source AI Tools',
    headline: 'Community-driven agent toolkits',
    description: 'Open source AI skills and agent packs you can inspect, fork, and extend.',
    seoTitle: 'Best Open Source AI Tools 2026 | AI Pass Discovery',
    seoDescription: 'Top open source AI tools and agent skill packs for developers.',
    toolIds: ['app_agent_toolkit_oss', 'app_iot_anomaly_detector'],
  },
  {
    slug: 'free',
    title: 'Best Free AI Tools',
    headline: 'Freemium & free-tier AI apps',
    description: 'Start with free and freemium AI tools — upgrade when you scale.',
    seoTitle: 'Best Free AI Tools 2026 | AI Pass Discovery',
    seoDescription: 'Free and freemium AI tools for teams getting started with AI automation.',
    toolIds: ['app_agent_toolkit_oss', 'app_customer_support_ai', 'app_marketing_insights_ai'],
  },
  {
    slug: 'enterprise',
    title: 'Best Enterprise AI Tools',
    headline: 'Certified, governance-ready AI for large orgs',
    description: 'Enterprise-grade AI with trust certification, SSO, and compliance controls.',
    seoTitle: 'Best Enterprise AI Tools 2026 | AI Pass Discovery',
    seoDescription: 'Enterprise AI tools with certification, governance, and private deployment options.',
    toolIds: ['app_invoice_ai', 'app_compliance_guard', 'app_supply_chain_ai', 'app_legal_contract_ai'],
    membershipGate: 'enterprise',
  },
];

export const DISCOVERY_COLLECTIONS: Collection[] = [
  {
    id: 'col_startups',
    slug: 'startups',
    name: 'Startups',
    description: 'Lean AI stack for early-stage teams — freemium apps and open source skills.',
    audience: 'startups',
    toolIds: ['app_customer_support_ai', 'app_marketing_insights_ai', 'app_agent_toolkit_oss'],
    featured: true,
    editable: true,
  },
  {
    id: 'col_enterprise',
    slug: 'enterprise',
    name: 'Enterprise',
    description: 'Certified, governance-ready apps for regulated industries.',
    audience: 'enterprise',
    toolIds: ['app_invoice_ai', 'app_compliance_guard', 'app_supply_chain_ai', 'app_legal_contract_ai'],
    featured: true,
    editable: true,
  },
  {
    id: 'col_developers',
    slug: 'developers',
    name: 'Developers',
    description: 'Agent skills, RAG packs, and dev tooling for building on AI Pass.',
    audience: 'developers',
    toolIds: ['app_agent_toolkit_oss', 'app_knowledge_pipeline_pack', 'app_iot_anomaly_detector'],
    featured: true,
    editable: true,
  },
  {
    id: 'col_healthcare',
    slug: 'healthcare',
    name: 'Healthcare',
    description: 'Compliance-first AI for healthcare document processing and governance.',
    audience: 'healthcare',
    toolIds: ['app_compliance_guard', 'app_legal_contract_ai'],
    featured: false,
    editable: true,
  },
  {
    id: 'col_finance',
    slug: 'finance',
    name: 'Finance & Procurement',
    description: 'Invoice AI, supply chain scoring, and finance compliance in one collection.',
    audience: 'finance',
    toolIds: ['app_invoice_ai', 'app_supply_chain_ai', 'app_compliance_guard'],
    featured: true,
    editable: true,
  },
];

export const DISCOVERY_DEALS: DiscoveryDeal[] = [
  {
    id: 'deal_lifetime_invoice',
    title: 'Lifetime Deal — Invoice AI Pro',
    description: 'One-time payment for lifetime access to Invoice AI Pro tier.',
    discountPercent: 60,
    appIds: ['app_invoice_ai'],
    toolIds: ['app_invoice_ai'],
    validUntil: '2026-07-31T23:59:59Z',
    countdownEndsAt: '2026-07-31T23:59:59Z',
    code: 'LIFETIME60',
    dealType: 'lifetime',
    originalPrice: 1188,
    dealPrice: 475,
    savingsPercent: 60,
    featured: true,
  },
  {
    id: 'deal_q2_finance',
    title: '20% off Finance Apps',
    description: 'Save 20% on Invoice AI and finance automation packs this quarter.',
    discountPercent: 20,
    appIds: ['app_invoice_ai'],
    toolIds: ['app_invoice_ai'],
    validUntil: '2026-06-30T23:59:59Z',
    countdownEndsAt: '2026-06-30T23:59:59Z',
    code: 'FINANCE20',
    dealType: 'discount',
    originalPrice: 99,
    dealPrice: 79,
    savingsPercent: 20,
    featured: true,
  },
  {
    id: 'deal_support_bundle',
    title: 'Support AI Bundle',
    description: 'Customer Support AI + Sales Copilot bundle at 25% off.',
    discountPercent: 25,
    appIds: ['app_customer_support_ai', 'app_sales_copilot'],
    toolIds: ['app_customer_support_ai', 'app_sales_copilot'],
    validUntil: '2026-08-15T23:59:59Z',
    countdownEndsAt: '2026-08-15T23:59:59Z',
    dealType: 'bundle',
    originalPrice: 138,
    dealPrice: 104,
    savingsPercent: 25,
    featured: true,
  },
  {
    id: 'deal_enterprise_compliance',
    title: 'Enterprise Compliance Pack',
    description: 'Compliance Guard + Legal Contract AI — enterprise license at 30% off.',
    discountPercent: 30,
    appIds: ['app_compliance_guard', 'app_legal_contract_ai'],
    toolIds: ['app_compliance_guard', 'app_legal_contract_ai'],
    validUntil: '2026-09-30T23:59:59Z',
    countdownEndsAt: '2026-09-30T23:59:59Z',
    dealType: 'enterprise',
    originalPrice: 5000,
    dealPrice: 3500,
    savingsPercent: 30,
    featured: false,
  },
  {
    id: 'deal_hr_flash',
    title: 'Flash Sale — HR AI',
    description: 'Limited 48-hour flash sale on HR AI subscription.',
    discountPercent: 40,
    appIds: ['app_hr_ai'],
    toolIds: ['app_hr_ai'],
    validUntil: '2026-07-05T23:59:59Z',
    countdownEndsAt: '2026-07-05T23:59:59Z',
    code: 'HRFLASH40',
    dealType: 'limited_time',
    originalPrice: 79,
    dealPrice: 47,
    savingsPercent: 40,
    featured: true,
  },
  {
    id: 'deal_dev_oss',
    title: 'Developer Pack — OSS Toolkit',
    description: 'Free credits bundle with Agent Toolkit OSS install.',
    discountPercent: 100,
    appIds: ['app_agent_toolkit_oss'],
    toolIds: ['app_agent_toolkit_oss'],
    validUntil: '2026-12-31T23:59:59Z',
    countdownEndsAt: '2026-12-31T23:59:59Z',
    dealType: 'campaign',
    originalPrice: 0,
    dealPrice: 0,
    savingsPercent: 100,
    featured: false,
  },
  {
    id: 'deal_knowledge_rag',
    title: 'RAG Pipeline Launch Promo',
    description: '50% off Knowledge Pipeline Pack for the first 3 months.',
    discountPercent: 50,
    appIds: ['app_knowledge_pipeline_pack'],
    toolIds: ['app_knowledge_pipeline_pack'],
    validUntil: '2026-08-01T23:59:59Z',
    countdownEndsAt: '2026-08-01T23:59:59Z',
    code: 'RAG50',
    dealType: 'limited_time',
    originalPrice: 39,
    dealPrice: 20,
    savingsPercent: 50,
    featured: true,
  },
  {
    id: 'deal_supply_chain',
    title: 'Supply Chain AI — Pay-per-use Credit Bonus',
    description: 'Get 500 bonus credits with Supply Chain AI activation.',
    discountPercent: 15,
    appIds: ['app_supply_chain_ai'],
    toolIds: ['app_supply_chain_ai'],
    validUntil: '2026-10-31T23:59:59Z',
    countdownEndsAt: '2026-10-31T23:59:59Z',
    dealType: 'campaign',
    savingsPercent: 15,
    featured: false,
  },
];

export const SEED_NEWS: NewsArticle[] = [
  {
    id: 'news_gpt5_launch',
    slug: 'gpt-5-provider-update',
    title: 'GPT-5 Now Available in AI Pass Provider Hub',
    summary: 'All Professional and Power members can route requests to GPT-5 via unified wallet billing.',
    category: 'llm_update',
    publishedAt: '2026-06-15T10:00:00Z',
    source: 'AI Pass Labs',
  },
  {
    id: 'news_invoice_v21',
    slug: 'invoice-ai-v21-launch',
    title: 'Invoice AI v2.1 — Fraud Detection Upgrade',
    summary: 'New anomaly scoring model reduces false positives by 34% in enterprise deployments.',
    category: 'product_launch',
    publishedAt: '2026-06-10T14:30:00Z',
    source: 'AI Pass Labs',
    toolIds: ['app_invoice_ai'],
  },
  {
    id: 'news_marketplace_deals',
    slug: 'summer-deals-hub',
    title: 'Summer Deals Hub — 8 Limited-Time Offers',
    summary: 'Discovery Hub launches Deals Hub with lifetime deals, bundles, and enterprise packages.',
    category: 'marketplace_update',
    publishedAt: '2026-06-01T09:00:00Z',
    source: 'AI Pass Marketplace',
  },
  {
    id: 'news_ai_summit',
    slug: 'ai-pass-summit-2026',
    title: 'AI Pass Summit 2026 — Registration Open',
    summary: 'Join enterprise AI leaders for governance, agents, and marketplace deep dives.',
    category: 'event',
    publishedAt: '2026-05-28T11:00:00Z',
    source: 'AI Pass Events',
    url: 'https://ai-pass.com/events/summit-2026',
  },
  {
    id: 'news_claude_opus',
    slug: 'claude-opus-4-provider',
    title: 'Claude Opus 4 Added to Provider Catalog',
    summary: 'Enterprise tenants can enable Claude Opus 4 with BYOK or platform routing.',
    category: 'llm_update',
    publishedAt: '2026-05-20T08:00:00Z',
    source: 'Provider Hub',
  },
];

export const SEED_RESEARCH: ResearchArticle[] = [
  {
    id: 'research_rag_benchmark',
    slug: 'enterprise-rag-benchmark-2026',
    title: 'Enterprise RAG Benchmark 2026',
    summary: 'Comparative study of retrieval accuracy across 12 production RAG pipelines.',
    type: 'benchmark',
    publishedAt: '2026-05-01T00:00:00Z',
    authors: ['AI Pass Research', 'Stanford HAI'],
    toolIds: ['app_knowledge_pipeline_pack'],
  },
  {
    id: 'research_invoice_ml',
    slug: 'invoice-extraction-accuracy-study',
    title: 'Invoice Extraction Accuracy in Multilingual AP',
    summary: 'Field-level accuracy analysis across 50k invoices in 8 languages.',
    type: 'paper',
    publishedAt: '2026-04-15T00:00:00Z',
    authors: ['AI Pass Labs', 'MIT CSAIL'],
    toolIds: ['app_invoice_ai'],
  },
  {
    id: 'research_ai_governance',
    slug: 'ai-governance-enterprise-report',
    title: 'AI Governance in Regulated Industries — 2026 Report',
    summary: 'Survey of 200 enterprises on compliance tooling, audit trails, and certification.',
    type: 'industry_report',
    publishedAt: '2026-03-20T00:00:00Z',
    authors: ['Gartner', 'AI Pass Trust Engine'],
    toolIds: ['app_compliance_guard'],
  },
  {
    id: 'research_agent_eval',
    slug: 'agent-reliability-benchmark',
    title: 'Production Agent Reliability Benchmark',
    summary: 'Task completion rates and failure modes across support, sales, and automation agents.',
    type: 'benchmark',
    publishedAt: '2026-02-10T00:00:00Z',
    authors: ['AI Pass Agent Studio'],
    toolIds: ['app_customer_support_ai', 'app_sales_copilot'],
  },
];

export const SEED_COMPARISONS: Comparison[] = [
  {
    toolAId: 'app_invoice_ai',
    toolBId: 'app_compliance_guard',
    slug: 'invoice-ai-vs-compliance-guard',
    title: 'Invoice AI vs Compliance Guard',
    summary: 'Finance automation vs enterprise governance — when to use each.',
    dimensions: [],
  },
  {
    toolAId: 'app_customer_support_ai',
    toolBId: 'app_sales_copilot',
    slug: 'customer-support-ai-vs-sales-copilot',
    title: 'Customer Support AI vs Sales Copilot',
    summary: 'Compare support and sales agent packs for CRM-heavy teams.',
    dimensions: [],
  },
  {
    toolAId: 'app_agent_toolkit_oss',
    toolBId: 'app_knowledge_pipeline_pack',
    slug: 'agent-toolkit-vs-knowledge-pipeline',
    title: 'Agent Toolkit OSS vs Knowledge Pipeline Pack',
    summary: 'Open source skills vs managed RAG pipeline for developers.',
    dimensions: [],
  },
];

export const BEST_AI_SLUGS = BEST_AI_PAGES.map((p) => p.slug);
