import type { Agent } from '@ai-pass/agent-studio';

const SKILL = {
  offerExtract: 'skill_offer_extraction',
  rules: 'skill_procurement_rules',
  scoring: 'skill_supplier_scoring',
  compliance: 'skill_policy_compliance',
  decision: 'skill_decision_engine',
} as const;

export const SUPPLY_CHAIN_AGENT_TYPES = [
  'sc_pricing',
  'sc_risk',
  'sc_compliance',
  'sc_esg',
  'sc_logistics',
  'sc_decision',
  'sc_planner',
  'sc_evaluator',
  'sc_output',
] as const;

export type SupplyChainAgentType = (typeof SUPPLY_CHAIN_AGENT_TYPES)[number];

/** Supply Chain AI Agent Studio definitions — routed via platform skill executor */
export const SUPPLY_CHAIN_AGENTS: Array<
  Omit<Agent, 'createdAt' | 'updatedAt' | 'currentVersion'> & { id: string }
> = [
  {
    id: 'agent_sc_pricing',
    name: 'Pricing Agent',
    description: 'Benchmark pricing, TCO analysis, and cost competitiveness',
    type: 'sc_pricing',
    agentType: 'Decision',
    skillIds: [SKILL.scoring],
    inputSchema: { type: 'object', properties: { offerId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { decision: { type: 'string' }, benchmark: { type: 'number' } } },
    riskLevel: 'medium',
    status: 'active',
  },
  {
    id: 'agent_sc_risk',
    name: 'Risk Agent',
    description: 'Supplier risk scoring, financial health, and geopolitical exposure',
    type: 'sc_risk',
    agentType: 'Decision',
    skillIds: [SKILL.rules],
    inputSchema: { type: 'object', properties: { supplierId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { decision: { type: 'string' }, riskScore: { type: 'number' } } },
    riskLevel: 'high',
    status: 'active',
  },
  {
    id: 'agent_sc_compliance',
    name: 'Compliance Agent',
    description: 'Regulatory compliance, certifications, and policy adherence',
    type: 'sc_compliance',
    agentType: 'Decision',
    skillIds: [SKILL.compliance],
    inputSchema: { type: 'object', properties: { offerId: { type: 'string' }, policyIds: { type: 'array' } } },
    outputSchema: { type: 'object', properties: { decision: { type: 'string' }, violations: { type: 'array' } } },
    riskLevel: 'high',
    status: 'active',
  },
  {
    id: 'agent_sc_esg',
    name: 'ESG Agent',
    description: 'Environmental, social, and governance scoring',
    type: 'sc_esg',
    agentType: 'Decision',
    skillIds: [SKILL.scoring],
    inputSchema: { type: 'object', properties: { supplierId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { decision: { type: 'string' }, esgScore: { type: 'number' } } },
    riskLevel: 'medium',
    status: 'active',
  },
  {
    id: 'agent_sc_logistics',
    name: 'Logistics Agent',
    description: 'Delivery timelines, incoterms, and supply chain resilience',
    type: 'sc_logistics',
    agentType: 'Decision',
    skillIds: [SKILL.rules],
    inputSchema: { type: 'object', properties: { offerId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { decision: { type: 'string' }, leadTimeDays: { type: 'number' } } },
    riskLevel: 'medium',
    status: 'active',
  },
  {
    id: 'agent_sc_decision',
    name: 'Decision Agent',
    description: 'Final award recommendation with explainability',
    type: 'sc_decision',
    agentType: 'Decision',
    skillIds: [SKILL.decision],
    inputSchema: { type: 'object', properties: { eventId: { type: 'string' }, evaluationId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { decision: { type: 'string' }, recommendedOfferId: { type: 'string' } } },
    riskLevel: 'high',
    status: 'active',
  },
  {
    id: 'agent_sc_planner',
    name: 'Planner Agent',
    description: 'Orchestrates evaluation workflow and agent sequencing',
    type: 'sc_planner',
    agentType: 'Workflow',
    skillIds: [SKILL.decision],
    inputSchema: { type: 'object', properties: { eventId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { plan: { type: 'array' } } },
    riskLevel: 'low',
    status: 'active',
  },
  {
    id: 'agent_sc_evaluator',
    name: 'Evaluator Agent',
    description: 'Multi-criteria scoring and ranking synthesis',
    type: 'sc_evaluator',
    agentType: 'Decision',
    skillIds: [SKILL.scoring],
    inputSchema: { type: 'object', properties: { eventId: { type: 'string' }, offerIds: { type: 'array' } } },
    outputSchema: { type: 'object', properties: { rankings: { type: 'array' } } },
    riskLevel: 'high',
    status: 'active',
  },
  {
    id: 'agent_sc_output',
    name: 'Output Composer',
    description: 'Generates decision memos, reports, and evidence packs',
    type: 'sc_output',
    agentType: 'Document',
    skillIds: [SKILL.offerExtract],
    inputSchema: { type: 'object', properties: { evaluationId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { artifacts: { type: 'array' } } },
    riskLevel: 'low',
    status: 'active',
  },
];

export const SUPPLY_CHAIN_SKILLS = [
  { name: 'OfferExtractionSkill', category: 'data' as const, creditCost: 15, description: 'Parse supplier offers from PDF, Excel, CSV' },
  { name: 'ProcurementRulesSkill', category: 'decision' as const, creditCost: 20, description: 'Evaluate offers against procurement rules' },
  { name: 'SupplierScoringSkill', category: 'decision' as const, creditCost: 25, description: 'Weighted multi-criteria supplier scoring' },
  { name: 'PolicyComplianceSkill', category: 'decision' as const, creditCost: 18, description: 'Check offer compliance against procurement policies' },
];
