import type { OutputFormat, StructuredOutput } from '../types.js';

export interface ComposeOptions {
  title?: string;
  author?: string;
}

export class OutputComposer {
  compose(
    base: StructuredOutput,
    format: OutputFormat,
    options: ComposeOptions = {},
  ): StructuredOutput & { formatted: string | Record<string, unknown> } {
    switch (format) {
      case 'json':
        return { ...base, format, formatted: this.toJson(base) };
      case 'pdf_stub':
        return { ...base, format, formatted: this.toPdfStub(base, options) };
      case 'executive_summary':
        return { ...base, format, formatted: this.toExecutiveSummary(base, options) };
      case 'business_report':
        return { ...base, format, formatted: this.toBusinessReport(base, options) };
      case 'workflow_result':
        return { ...base, format, formatted: this.toWorkflowResult(base) };
      case 'decision':
        return { ...base, format, formatted: this.toDecision(base) };
      case 'evidence':
        return { ...base, format, formatted: this.toEvidence(base) };
      default:
        return { ...base, format: 'json', formatted: this.toJson(base) };
    }
  }

  private toJson(output: StructuredOutput): Record<string, unknown> {
    return {
      decision: output.decision,
      confidence: output.confidence,
      evidence: output.evidence,
      result: output.result,
      needsInfo: output.needsInfo,
    };
  }

  private toPdfStub(output: StructuredOutput, options: ComposeOptions): string {
    return [
      `%PDF-1.4 stub`,
      `Title: ${options.title ?? 'AI-Pass Runtime Report'}`,
      `Decision: ${output.decision}`,
      `Confidence: ${(output.confidence * 100).toFixed(1)}%`,
      `Evidence items: ${output.evidence.length}`,
      `Generated by AI-Pass Runtime · ${new Date().toISOString()}`,
    ].join('\n');
  }

  private toExecutiveSummary(output: StructuredOutput, options: ComposeOptions): string {
    const lines = [
      `# ${options.title ?? 'Executive Summary'}`,
      '',
      `**Decision:** ${output.decision}`,
      `**Confidence:** ${(output.confidence * 100).toFixed(0)}%`,
    ];
    if (output.needsInfo) {
      lines.push('', '⚠ Additional information required before final decision.');
      if (output.missingFields?.length) {
        lines.push(`Missing: ${output.missingFields.join(', ')}`);
      }
    }
    if (output.evidence.length > 0) {
      lines.push('', '## Key Evidence');
      for (const e of output.evidence.slice(0, 3)) {
        lines.push(`- ${e.source}: ${e.excerpt.slice(0, 120)}`);
      }
    }
    return lines.join('\n');
  }

  private toBusinessReport(output: StructuredOutput, options: ComposeOptions): string {
    return [
      `BUSINESS REPORT — ${options.title ?? 'Runtime Execution'}`,
      `Decision: ${output.decision}`,
      `Confidence Score: ${output.confidence}`,
      `Evidence Count: ${output.evidence.length}`,
      `Result Keys: ${Object.keys(output.result).join(', ')}`,
    ].join('\n');
  }

  private toWorkflowResult(output: StructuredOutput): Record<string, unknown> {
    return {
      workflowStatus: output.needsInfo ? 'needs_info' : 'completed',
      decision: output.decision,
      confidence: output.confidence,
      outputs: output.result,
    };
  }

  private toDecision(output: StructuredOutput): Record<string, unknown> {
    return {
      decision: output.decision,
      confidence: output.confidence,
      needsInfo: output.needsInfo ?? false,
    };
  }

  private toEvidence(output: StructuredOutput): Record<string, unknown> {
    return {
      items: output.evidence,
      count: output.evidence.length,
      decision: output.decision,
    };
  }
}

export const defaultOutputComposer = new OutputComposer();
