import type { Application, DeveloperProfile, Campaign, Deal, Review, Collection, IndustryPack, Coupon, Bundle } from './types.js';

export const SEED_DEVELOPERS: Omit<DeveloperProfile, 'createdAt'>[] = [
  {
    id: 'dev_ai_pass',
    email: 'platform@ai-pass.com',
    name: 'AI Pass Labs',
    company: 'AI Pass Inc.',
    verified: true,
    slug: 'ai-pass-labs',
    bio: 'Official AI Pass platform developer — vertical AI solutions and agent skills.',
    website: 'https://ai-pass.com',
    appCount: 4,
    skillCount: 8,
    totalRevenue: 125000,
    reputationScore: 4.9,
    badges: [
      { type: 'verified_developer', label: 'Verified Developer', issuedAt: '2025-01-01T00:00:00Z' },
      { type: 'enterprise_ready', label: 'Enterprise Ready', issuedAt: '2025-01-01T00:00:00Z' },
    ],
  },
  {
    id: 'dev_acme',
    email: 'dev@acme.ai',
    name: 'Acme AI Studio',
    company: 'Acme Corp',
    verified: true,
    slug: 'acme-ai-studio',
    bio: 'Enterprise automation packs and compliance skills.',
    appCount: 2,
    skillCount: 5,
    totalRevenue: 42000,
    reputationScore: 4.7,
    badges: [{ type: 'verified_developer', label: 'Verified Developer', issuedAt: '2025-03-15T00:00:00Z' }],
  },
  {
    id: 'dev_opensource',
    email: 'hello@opensource.ai',
    name: 'OpenSource Collective',
    verified: false,
    slug: 'opensource-collective',
    bio: 'Community-driven open source AI agent tools.',
    appCount: 1,
    skillCount: 3,
    totalRevenue: 0,
    reputationScore: 4.2,
    badges: [{ type: 'open_source', label: 'Open Source', issuedAt: '2025-06-01T00:00:00Z' }],
  },
];

export const SEED_APPS: Omit<Application, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Invoice AI',
    slug: 'invoice-ai',
    description: 'Full finance automation engine for invoice lifecycle — extraction, validation, approval routing, and fraud detection.',
    developerId: 'dev_ai_pass',
    appType: 'hosted_saas',
    category: 'finance',
    pricingModel: 'subscription',
    priceMonthly: 99,
    riskLevel: 'high',
    supportedPlatforms: ['web', 'desktop', 'mobile'],
    skillIds: ['skill_invoice_extract', 'skill_invoice_decision'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet'],
    tags: ['finance', 'invoices', 'automation', 'compliance'],
    permissions: ['documents.read', 'erp.write', 'wallet.deduct'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    sponsored: false,
    installCount: 1320,
    rating: 4.8,
    reviewCount: 89,
    version: '2.1.0',
  },
  {
    name: 'Supply Chain AI',
    slug: 'supply-chain-ai',
    description: 'Procurement offer evaluation, supplier scoring, and award decision automation with explainability.',
    developerId: 'dev_ai_pass',
    appType: 'hosted_saas',
    category: 'supply_chain',
    pricingModel: 'pay_per_use',
    pricePerUse: 2.5,
    riskLevel: 'high',
    supportedPlatforms: ['web', 'desktop'],
    skillIds: ['skill_offer_parse', 'skill_supplier_score'],
    modelsUsed: ['gpt-4o'],
    tags: ['procurement', 'supply-chain', 'scoring'],
    permissions: ['documents.read', 'wallet.deduct'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    sponsored: true,
    installCount: 890,
    rating: 4.9,
    reviewCount: 45,
    version: '1.4.0',
  },
  {
    name: 'Customer Support AI',
    slug: 'customer-support-ai',
    description: 'Voice + text multi-language support agent with CRM integration and intelligent escalation.',
    developerId: 'dev_ai_pass',
    appType: 'agent_pack',
    category: 'customer_support',
    pricingModel: 'freemium',
    priceMonthly: 49,
    riskLevel: 'medium',
    supportedPlatforms: ['web', 'mobile'],
    skillIds: ['skill_support_chat', 'skill_voice_transcribe'],
    modelsUsed: ['gpt-4o', 'whisper-1'],
    tags: ['support', 'voice', 'chat', 'crm'],
    permissions: ['crm.read', 'crm.write', 'wallet.deduct'],
    certified: false,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: false,
    sponsored: false,
    installCount: 2100,
    rating: 4.7,
    reviewCount: 156,
    version: '3.0.0',
  },
  {
    name: 'Compliance AI',
    slug: 'compliance-ai',
    description: 'Enterprise compliance operations — ISO, GDPR, SOC2, AI governance, trust center, and regulatory automation.',
    developerId: 'dev_ai_pass',
    appType: 'hosted_saas',
    category: 'compliance',
    pricingModel: 'subscription',
    priceMonthly: 149,
    riskLevel: 'high',
    supportedPlatforms: ['web', 'desktop'],
    skillIds: ['skill_compliance_check', 'skill_policy_generate'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet'],
    tags: ['compliance', 'iso', 'gdpr', 'governance', 'trust'],
    permissions: ['governance.read', 'documents.read', 'wallet.deduct'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    sponsored: false,
    installCount: 780,
    rating: 4.9,
    reviewCount: 52,
    version: '1.0.0',
  },
  {
    name: 'Presence Audit',
    slug: 'presence-audit',
    description: 'AI Visibility Intelligence Platform — audit, optimize, and monitor brand presence across ChatGPT, Claude, Gemini, and Perplexity.',
    developerId: 'dev_ai_pass',
    appType: 'hosted_saas',
    category: 'analytics',
    pricingModel: 'subscription',
    priceMonthly: 149,
    riskLevel: 'low',
    supportedPlatforms: ['web'],
    skillIds: ['skill_presence_audit'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet', 'gemini-1.5-pro'],
    tags: ['ai-visibility', 'presence', 'competitor-analysis', 'monitoring'],
    permissions: ['wallet.deduct', 'trust.read'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    sponsored: false,
    installCount: 680,
    rating: 4.8,
    reviewCount: 42,
    version: '1.0.0',
  },
  {
    name: 'Content AI',
    slug: 'content-ai',
    description: 'AI Detector & Humanizer — detect AI-generated text, humanize with confidence, and integrate with Trust Engine and Provider Hub.',
    developerId: 'dev_ai_pass',
    appType: 'hosted_saas',
    category: 'marketing',
    pricingModel: 'freemium',
    priceMonthly: 39,
    pricePerUse: 0.05,
    riskLevel: 'medium',
    supportedPlatforms: ['web'],
    skillIds: ['skill_content_detect', 'skill_content_humanize'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet', 'gemini-1.5-pro'],
    tags: ['writing', 'marketing', 'sales', 'compliance', 'education'],
    permissions: ['wallet.deduct', 'trust.read'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    sponsored: false,
    installCount: 520,
    rating: 4.8,
    reviewCount: 38,
    version: '1.0.0',
  },
  {
    name: 'HR AI',
    slug: 'hr-ai',
    description: 'Resume parsing, candidate screening, and onboarding automation for HR teams.',
    developerId: 'dev_acme',
    appType: 'automation_pack',
    category: 'hr',
    pricingModel: 'subscription',
    priceMonthly: 79,
    riskLevel: 'medium',
    supportedPlatforms: ['web'],
    skillIds: ['skill_resume_parse'],
    modelsUsed: ['gpt-4o', 'claude-3-haiku'],
    tags: ['hr', 'recruiting', 'onboarding'],
    permissions: ['documents.read', 'wallet.deduct'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: false,
    trending: true,
    sponsored: false,
    installCount: 540,
    rating: 4.5,
    reviewCount: 32,
    version: '1.2.0',
  },
  {
    name: 'Compliance Guard',
    slug: 'compliance-guard',
    description: 'Policy enforcement, risk registry, and AI governance for regulated industries.',
    developerId: 'dev_acme',
    appType: 'enterprise_app',
    category: 'compliance',
    pricingModel: 'enterprise_license',
    riskLevel: 'critical',
    supportedPlatforms: ['web', 'desktop'],
    skillIds: ['skill_compliance_check'],
    modelsUsed: ['gpt-4o', 'claude-3-opus'],
    tags: ['compliance', 'governance', 'enterprise'],
    permissions: ['governance.read', 'governance.write', 'wallet.deduct'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: false,
    sponsored: false,
    installCount: 210,
    rating: 4.9,
    reviewCount: 18,
    version: '2.0.0',
  },
  {
    name: 'Agent Toolkit OSS',
    slug: 'agent-toolkit-oss',
    description: 'Open source collection of reusable agent skills and workflow templates.',
    developerId: 'dev_opensource',
    appType: 'skill_pack',
    category: 'developer_tools',
    pricingModel: 'free',
    riskLevel: 'low',
    supportedPlatforms: ['web', 'desktop', 'mobile'],
    skillIds: ['skill_generic_parse'],
    modelsUsed: ['gpt-4o-mini'],
    tags: ['open-source', 'developer', 'agents'],
    permissions: ['wallet.deduct'],
    certified: false,
    enterpriseReady: false,
    openSource: true,
    featured: false,
    trending: true,
    sponsored: false,
    installCount: 3200,
    rating: 4.3,
    reviewCount: 210,
    version: '0.9.0',
  },
  {
    name: 'Legal Contract AI',
    slug: 'legal-contract-ai',
    description: 'Contract review, clause extraction, and risk flagging for legal teams.',
    developerId: 'dev_acme',
    appType: 'hosted_saas',
    category: 'legal',
    pricingModel: 'subscription',
    priceMonthly: 149,
    riskLevel: 'high',
    supportedPlatforms: ['web', 'desktop'],
    skillIds: ['skill_contract_parse', 'skill_compliance_check'],
    modelsUsed: ['claude-3-opus', 'gpt-4o'],
    tags: ['legal', 'contracts', 'compliance'],
    permissions: ['documents.read', 'wallet.deduct'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: false,
    sponsored: false,
    installCount: 380,
    rating: 4.6,
    reviewCount: 24,
    version: '1.0.0',
  },
  {
    name: 'Marketing Insights AI',
    slug: 'marketing-insights-ai',
    description: 'Campaign analytics, audience segmentation, and content optimization.',
    developerId: 'dev_ai_pass',
    appType: 'external_app',
    category: 'marketing',
    pricingModel: 'freemium',
    priceMonthly: 59,
    riskLevel: 'medium',
    supportedPlatforms: ['web'],
    skillIds: ['skill_sentiment_analytics'],
    modelsUsed: ['gpt-4o'],
    tags: ['marketing', 'analytics', 'campaigns'],
    permissions: ['crm.read', 'wallet.deduct'],
    certified: false,
    enterpriseReady: false,
    openSource: false,
    featured: false,
    trending: true,
    sponsored: false,
    installCount: 920,
    rating: 4.4,
    reviewCount: 67,
    version: '2.2.0',
  },
  {
    name: 'Vision QA Inspector',
    slug: 'vision-qa-inspector',
    description: 'Computer vision quality inspection for manufacturing lines.',
    developerId: 'dev_acme',
    appType: 'github_app',
    category: 'vision_ai',
    pricingModel: 'pay_per_use',
    pricePerUse: 0.5,
    riskLevel: 'medium',
    supportedPlatforms: ['web', 'desktop'],
    skillIds: ['skill_vision_inspect'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet'],
    tags: ['vision', 'manufacturing', 'qa'],
    permissions: ['documents.read', 'wallet.deduct'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: false,
    trending: true,
    sponsored: false,
    installCount: 450,
    rating: 4.7,
    reviewCount: 19,
    version: '1.1.0',
  },
  {
    name: 'Sales AI',
    slug: 'sales-ai',
    description: 'AI-powered Revenue Operating System — email, LinkedIn, proposals, CRM, campaigns, and agents.',
    developerId: 'dev_ai_pass',
    appType: 'agent_pack',
    category: 'sales',
    pricingModel: 'freemium',
    priceMonthly: 39,
    riskLevel: 'medium',
    supportedPlatforms: ['web', 'mobile'],
    skillIds: ['skill_lead_score', 'skill_api_crm_sync', 'skill_sales_email', 'skill_sales_proposal'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet'],
    tags: ['sales', 'crm', 'leads', 'email', 'linkedin', 'proposals', 'campaigns'],
    permissions: ['crm.read', 'crm.write', 'wallet.deduct'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    sponsored: true,
    installCount: 2400,
    rating: 4.8,
    reviewCount: 142,
    version: '1.0.0',
  },
  {
    name: 'Knowledge Pipeline Pack',
    slug: 'knowledge-pipeline-pack',
    description: 'Pre-built RAG ingestion, enrichment, and retrieval skills for enterprise knowledge bases.',
    developerId: 'dev_ai_pass',
    appType: 'skill_pack',
    category: 'knowledge',
    pricingModel: 'subscription',
    priceMonthly: 39,
    riskLevel: 'low',
    supportedPlatforms: ['web'],
    skillIds: ['skill_rag_retrieve', 'skill_doc_chunk'],
    modelsUsed: ['gpt-4o-mini', 'text-embedding-3-large'],
    tags: ['knowledge', 'rag', 'retrieval'],
    permissions: ['documents.read', 'wallet.deduct'],
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: false,
    sponsored: false,
    installCount: 760,
    rating: 4.8,
    reviewCount: 41,
    version: '1.0.0',
  },
  {
    name: 'IoT Anomaly Detector',
    slug: 'iot-anomaly-detector',
    description: 'Edge-ready anomaly detection for IoT sensor streams.',
    developerId: 'dev_opensource',
    appType: 'private_app',
    category: 'iot',
    pricingModel: 'enterprise_license',
    riskLevel: 'high',
    supportedPlatforms: ['desktop'],
    skillIds: ['skill_iot_anomaly'],
    modelsUsed: ['gpt-4o-mini'],
    tags: ['iot', 'edge', 'anomaly'],
    permissions: ['wallet.deduct'],
    certified: false,
    enterpriseReady: true,
    openSource: true,
    featured: false,
    trending: false,
    sponsored: false,
    installCount: 95,
    rating: 4.1,
    reviewCount: 8,
    version: '0.5.0',
  },
];

export const SEED_SKILLS: (Parameters<import('./skill-registry.js').SkillRegistry['register']>[0] & { id: string })[] = [
  {
    id: 'skill_invoice_extract',
    name: 'InvoiceExtractionSkill',
    slug: 'invoice-extraction',
    description: 'Extract structured fields from invoice PDFs and images.',
    version: '1.2.0',
    developerId: 'dev_ai_pass',
    category: 'parsing',
    riskLevel: 'medium',
    planTierRequired: 'free',
    inputSchema: { type: 'object', properties: { document: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { fields: { type: 'object' } } },
    creditCost: 10,
    deterministic: false,
    explainabilityRequired: true,
    platforms: ['web', 'desktop'],
    tags: ['invoice', 'ocr', 'finance'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: true,
    featured: true,
    trending: true,
    installCount: 890,
    rating: 4.8,
    reviewCount: 42,
  },
  {
    id: 'skill_invoice_decision',
    name: 'InvoiceDecisionSkill',
    slug: 'invoice-decision',
    description: 'Approve, reject, or flag invoices based on business rules.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'decision',
    riskLevel: 'high',
    planTierRequired: 'professional',
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object', properties: { decision: { enum: ['PASS', 'FAIL', 'NEEDS_INFO'] } } },
    creditCost: 25,
    deterministic: true,
    explainabilityRequired: true,
    platforms: ['web', 'desktop', 'mobile'],
    tags: ['invoice', 'approval', 'decision'],
    modelsUsed: ['claude-3-5-sonnet'],
    lifecycleStatus: 'published',
    certified: true,
    featured: false,
    trending: true,
    installCount: 650,
    rating: 4.9,
    reviewCount: 28,
  },
  {
    id: 'skill_offer_parse',
    name: 'OfferParsingSkill',
    slug: 'offer-parsing',
    description: 'Parse supplier offers from PDF, XLSX, and CSV formats.',
    version: '1.1.0',
    developerId: 'dev_ai_pass',
    category: 'parsing',
    riskLevel: 'medium',
    planTierRequired: 'professional',
    inputSchema: { type: 'object', properties: { document: { type: 'string' } } },
    outputSchema: { type: 'object' },
    creditCost: 15,
    deterministic: false,
    explainabilityRequired: false,
    platforms: ['web'],
    tags: ['procurement', 'parsing'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: true,
    featured: false,
    trending: false,
    installCount: 320,
    rating: 4.7,
    reviewCount: 15,
  },
  {
    id: 'skill_supplier_score',
    name: 'SupplierScoringSkill',
    slug: 'supplier-scoring',
    description: 'Score and rank supplier offers with explainable criteria.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'analytics',
    riskLevel: 'high',
    planTierRequired: 'professional',
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object', properties: { score: { type: 'number' } } },
    creditCost: 30,
    deterministic: true,
    explainabilityRequired: true,
    platforms: ['web', 'desktop'],
    tags: ['procurement', 'scoring'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: true,
    featured: true,
    trending: false,
    installCount: 280,
    rating: 4.8,
    reviewCount: 12,
  },
  {
    id: 'skill_support_chat',
    name: 'SupportChatSkill',
    slug: 'support-chat',
    description: 'Multi-language customer support chat with context retention.',
    version: '2.0.0',
    developerId: 'dev_ai_pass',
    category: 'communication',
    riskLevel: 'medium',
    planTierRequired: 'free',
    inputSchema: { type: 'object', properties: { message: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { response: { type: 'string' } } },
    creditCost: 5,
    deterministic: false,
    explainabilityRequired: false,
    platforms: ['web', 'mobile'],
    tags: ['support', 'chat'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: false,
    featured: true,
    trending: true,
    installCount: 1500,
    rating: 4.6,
    reviewCount: 88,
  },
  {
    id: 'skill_presence_audit',
    name: 'PresenceAuditSkill',
    slug: 'presence-audit',
    description: 'Multi-provider AI visibility audit with competitor analysis and optimization recommendations.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'analytics',
    riskLevel: 'low',
    planTierRequired: 'professional',
    inputSchema: { type: 'object', properties: { companyId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { score: { type: 'number' }, report: { type: 'object' } } },
    creditCost: 10,
    deterministic: false,
    explainabilityRequired: true,
    platforms: ['web'],
    tags: ['presence', 'visibility', 'audit'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet', 'gemini-1.5-pro'],
    lifecycleStatus: 'published',
    certified: true,
    featured: true,
    trending: true,
    installCount: 680,
    rating: 4.8,
    reviewCount: 42,
  },
  {
    id: 'skill_content_detect',
    name: 'ContentDetectSkill',
    slug: 'content-detect',
    description: 'AI-generated text detection with sentence-level probability scoring.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'analytics',
    riskLevel: 'low',
    planTierRequired: 'free',
    inputSchema: { type: 'object', properties: { text: { type: 'string' } } },
    outputSchema: {
      type: 'object',
      properties: { aiScore: { type: 'number' }, humanScore: { type: 'number' } },
    },
    creditCost: 1,
    deterministic: false,
    explainabilityRequired: true,
    platforms: ['web'],
    tags: ['writing', 'detection', 'compliance'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet'],
    lifecycleStatus: 'published',
    certified: true,
    featured: true,
    trending: true,
    installCount: 420,
    rating: 4.7,
    reviewCount: 28,
  },
  {
    id: 'skill_content_humanize',
    name: 'ContentHumanizeSkill',
    slug: 'content-humanize',
    description: 'Humanize AI-generated text with tone control and multi-model routing.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'communication',
    riskLevel: 'medium',
    planTierRequired: 'professional',
    inputSchema: {
      type: 'object',
      properties: { text: { type: 'string' }, tone: { type: 'string' } },
    },
    outputSchema: { type: 'object', properties: { humanizedText: { type: 'string' } } },
    creditCost: 5,
    deterministic: false,
    explainabilityRequired: false,
    platforms: ['web'],
    tags: ['writing', 'humanize', 'marketing'],
    modelsUsed: ['gpt-4o', 'claude-3-5-sonnet', 'gemini-1.5-pro'],
    lifecycleStatus: 'published',
    certified: true,
    featured: true,
    trending: true,
    installCount: 380,
    rating: 4.8,
    reviewCount: 35,
  },
  {
    id: 'skill_voice_transcribe',
    name: 'VoiceTranscriptionSkill',
    slug: 'voice-transcription',
    description: 'Transcribe voice calls and audio for support workflows.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'voice',
    riskLevel: 'low',
    planTierRequired: 'professional',
    inputSchema: { type: 'object', properties: { audio: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { transcript: { type: 'string' } } },
    creditCost: 8,
    deterministic: false,
    explainabilityRequired: false,
    platforms: ['web', 'mobile'],
    tags: ['voice', 'transcription'],
    modelsUsed: ['whisper-1'],
    lifecycleStatus: 'published',
    certified: false,
    featured: false,
    trending: true,
    installCount: 720,
    rating: 4.5,
    reviewCount: 34,
  },
  {
    id: 'skill_resume_parse',
    name: 'ResumeParsingSkill',
    slug: 'resume-parsing',
    description: 'Extract structured candidate data from resumes.',
    version: '1.0.0',
    developerId: 'dev_acme',
    category: 'parsing',
    riskLevel: 'medium',
    planTierRequired: 'professional',
    inputSchema: { type: 'object', properties: { document: { type: 'string' } } },
    outputSchema: { type: 'object' },
    creditCost: 12,
    deterministic: false,
    explainabilityRequired: false,
    platforms: ['web'],
    tags: ['hr', 'resume'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: true,
    featured: false,
    trending: false,
    installCount: 410,
    rating: 4.4,
    reviewCount: 22,
  },
  {
    id: 'skill_compliance_check',
    name: 'ComplianceCheckSkill',
    slug: 'compliance-check',
    description: 'Validate AI outputs against regulatory and policy requirements.',
    version: '1.0.0',
    developerId: 'dev_acme',
    category: 'compliance',
    riskLevel: 'critical',
    planTierRequired: 'enterprise',
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object', properties: { compliant: { type: 'boolean' } } },
    creditCost: 40,
    deterministic: true,
    explainabilityRequired: true,
    platforms: ['web', 'desktop'],
    tags: ['compliance', 'governance'],
    modelsUsed: ['claude-3-opus'],
    lifecycleStatus: 'published',
    certified: true,
    featured: true,
    trending: false,
    installCount: 180,
    rating: 4.9,
    reviewCount: 9,
  },
  {
    id: 'skill_generic_parse',
    name: 'GenericDocumentParser',
    slug: 'generic-document-parser',
    description: 'Open source document parsing skill for any structured extraction.',
    version: '0.9.0',
    developerId: 'dev_opensource',
    category: 'parsing',
    riskLevel: 'low',
    planTierRequired: 'free',
    inputSchema: { type: 'object', properties: { document: { type: 'string' } } },
    outputSchema: { type: 'object' },
    creditCost: 3,
    deterministic: false,
    explainabilityRequired: false,
    permissions: ['documents.read', 'wallet.deduct'],
    compatibleModels: ['gpt-4o-mini'],
    dependencies: [],
    platforms: ['web', 'desktop', 'mobile'],
    tags: ['open-source', 'parsing'],
    modelsUsed: ['gpt-4o-mini'],
    lifecycleStatus: 'published',
    certified: false,
    featured: false,
    trending: true,
    installCount: 2100,
    rating: 4.2,
    reviewCount: 95,
  },
  {
    id: 'skill_contract_parse',
    name: 'ContractParsingSkill',
    slug: 'contract-parsing',
    description: 'Extract clauses, parties, and obligations from legal contracts.',
    version: '1.0.0',
    developerId: 'dev_acme',
    category: 'parsing',
    riskLevel: 'high',
    planTierRequired: 'professional',
    inputSchema: { type: 'object', properties: { document: { type: 'string' } } },
    outputSchema: { type: 'object' },
    creditCost: 20,
    deterministic: false,
    explainabilityRequired: true,
    permissions: ['documents.read', 'wallet.deduct'],
    compatibleModels: ['claude-3-opus', 'gpt-4o'],
    dependencies: [],
    platforms: ['web'],
    tags: ['legal', 'contracts'],
    modelsUsed: ['claude-3-opus'],
    lifecycleStatus: 'published',
    certified: true,
    featured: false,
    trending: false,
    installCount: 220,
    rating: 4.5,
    reviewCount: 11,
  },
  {
    id: 'skill_sentiment_analytics',
    name: 'SentimentAnalyticsSkill',
    slug: 'sentiment-analytics',
    description: 'Analyze campaign and social sentiment with trend detection.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'analytics',
    riskLevel: 'low',
    planTierRequired: 'free',
    inputSchema: { type: 'object', properties: { text: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { sentiment: { type: 'string' } } },
    creditCost: 5,
    deterministic: false,
    explainabilityRequired: false,
    permissions: ['wallet.deduct'],
    compatibleModels: ['gpt-4o'],
    dependencies: [],
    platforms: ['web'],
    tags: ['marketing', 'analytics'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: false,
    featured: false,
    trending: true,
    installCount: 680,
    rating: 4.3,
    reviewCount: 29,
  },
  {
    id: 'skill_vision_inspect',
    name: 'VisionInspectionSkill',
    slug: 'vision-inspection',
    description: 'Detect defects and anomalies in product images.',
    version: '1.0.0',
    developerId: 'dev_acme',
    category: 'vision',
    riskLevel: 'medium',
    planTierRequired: 'professional',
    inputSchema: { type: 'object', properties: { image: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { defects: { type: 'array' } } },
    creditCost: 15,
    deterministic: false,
    explainabilityRequired: true,
    permissions: ['documents.read', 'wallet.deduct'],
    compatibleModels: ['gpt-4o'],
    dependencies: [],
    platforms: ['web', 'desktop'],
    tags: ['vision', 'manufacturing'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: true,
    featured: true,
    trending: false,
    installCount: 340,
    rating: 4.6,
    reviewCount: 14,
  },
  {
    id: 'skill_lead_score',
    name: 'LeadScoringSkill',
    slug: 'lead-scoring',
    description: 'Score sales leads based on firmographic and behavioral signals.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'decision',
    riskLevel: 'medium',
    planTierRequired: 'professional',
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object', properties: { score: { type: 'number' } } },
    creditCost: 12,
    deterministic: true,
    explainabilityRequired: true,
    permissions: ['crm.read', 'wallet.deduct'],
    compatibleModels: ['gpt-4o'],
    dependencies: [],
    platforms: ['web', 'mobile'],
    tags: ['sales', 'scoring'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: true,
    featured: false,
    trending: true,
    installCount: 520,
    rating: 4.4,
    reviewCount: 31,
  },
  {
    id: 'skill_api_crm_sync',
    name: 'CrmSyncSkill',
    slug: 'crm-sync',
    description: 'Sync leads and activities with external CRM APIs.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'api_integration',
    riskLevel: 'medium',
    planTierRequired: 'professional',
    inputSchema: { type: 'object', properties: { record: { type: 'object' } } },
    outputSchema: { type: 'object', properties: { synced: { type: 'boolean' } } },
    creditCost: 8,
    deterministic: true,
    explainabilityRequired: false,
    permissions: ['crm.read', 'crm.write', 'wallet.deduct'],
    compatibleModels: ['gpt-4o-mini'],
    dependencies: ['skill_lead_score'],
    platforms: ['web'],
    tags: ['crm', 'api', 'integration'],
    modelsUsed: ['gpt-4o-mini'],
    lifecycleStatus: 'published',
    certified: true,
    featured: false,
    trending: false,
    installCount: 290,
    rating: 4.5,
    reviewCount: 17,
  },
  {
    id: 'skill_rag_retrieve',
    name: 'RagRetrievalSkill',
    slug: 'rag-retrieval',
    description: 'Semantic retrieval over indexed knowledge bases.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'retrieval',
    riskLevel: 'low',
    planTierRequired: 'professional',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { chunks: { type: 'array' } } },
    creditCost: 6,
    deterministic: false,
    explainabilityRequired: false,
    permissions: ['documents.read', 'wallet.deduct'],
    compatibleModels: ['gpt-4o-mini', 'text-embedding-3-large'],
    dependencies: ['skill_doc_chunk'],
    platforms: ['web'],
    tags: ['rag', 'knowledge', 'retrieval'],
    modelsUsed: ['text-embedding-3-large'],
    lifecycleStatus: 'published',
    certified: true,
    featured: true,
    trending: true,
    installCount: 890,
    rating: 4.7,
    reviewCount: 44,
  },
  {
    id: 'skill_doc_chunk',
    name: 'DocumentChunkingSkill',
    slug: 'document-chunking',
    description: 'Chunk and enrich documents for RAG pipelines.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'knowledge',
    riskLevel: 'low',
    planTierRequired: 'free',
    inputSchema: { type: 'object', properties: { document: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { chunks: { type: 'array' } } },
    creditCost: 4,
    deterministic: true,
    explainabilityRequired: false,
    permissions: ['documents.read', 'wallet.deduct'],
    compatibleModels: ['gpt-4o-mini'],
    dependencies: [],
    platforms: ['web'],
    tags: ['knowledge', 'chunking'],
    modelsUsed: ['gpt-4o-mini'],
    lifecycleStatus: 'published',
    certified: true,
    featured: false,
    trending: false,
    installCount: 610,
    rating: 4.6,
    reviewCount: 26,
  },
  {
    id: 'skill_iot_anomaly',
    name: 'IotAnomalySkill',
    slug: 'iot-anomaly',
    description: 'Detect anomalies in IoT sensor time-series data.',
    version: '0.5.0',
    developerId: 'dev_opensource',
    category: 'analytics',
    riskLevel: 'high',
    planTierRequired: 'enterprise',
    inputSchema: { type: 'object', properties: { readings: { type: 'array' } } },
    outputSchema: { type: 'object', properties: { anomalies: { type: 'array' } } },
    creditCost: 18,
    deterministic: true,
    explainabilityRequired: true,
    permissions: ['wallet.deduct'],
    compatibleModels: ['gpt-4o-mini'],
    dependencies: [],
    platforms: ['desktop'],
    tags: ['iot', 'edge', 'anomaly'],
    modelsUsed: ['gpt-4o-mini'],
    lifecycleStatus: 'published',
    certified: false,
    featured: false,
    trending: false,
    installCount: 75,
    rating: 4.0,
    reviewCount: 5,
  },
  {
    id: 'skill_ocr_extract',
    name: 'OcrExtractionSkill',
    slug: 'ocr-extraction',
    description: 'OCR extraction from scanned documents and images.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'ocr',
    riskLevel: 'medium',
    planTierRequired: 'free',
    inputSchema: { type: 'object', properties: { image: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { text: { type: 'string' } } },
    creditCost: 7,
    deterministic: false,
    explainabilityRequired: false,
    permissions: ['documents.read', 'wallet.deduct'],
    compatibleModels: ['gpt-4o'],
    dependencies: [],
    platforms: ['web', 'desktop', 'mobile'],
    tags: ['ocr', 'parsing'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: true,
    featured: false,
    trending: true,
    installCount: 1200,
    rating: 4.5,
    reviewCount: 58,
  },
  {
    id: 'skill_translate',
    name: 'TranslationSkill',
    slug: 'translation',
    description: 'Multi-language translation with domain terminology support.',
    version: '1.0.0',
    developerId: 'dev_ai_pass',
    category: 'translation',
    riskLevel: 'low',
    planTierRequired: 'free',
    inputSchema: { type: 'object', properties: { text: { type: 'string' }, targetLang: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { translation: { type: 'string' } } },
    creditCost: 4,
    deterministic: false,
    explainabilityRequired: false,
    permissions: ['wallet.deduct'],
    compatibleModels: ['gpt-4o', 'claude-3-haiku'],
    dependencies: [],
    platforms: ['web', 'mobile'],
    tags: ['translation', 'i18n'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'published',
    certified: false,
    featured: false,
    trending: true,
    installCount: 980,
    rating: 4.4,
    reviewCount: 52,
  },
  {
    id: 'skill_computer_navigate',
    name: 'ComputerNavigateSkill',
    slug: 'computer-navigate',
    description: 'Navigate and interact with desktop applications via computer action.',
    version: '0.8.0',
    developerId: 'dev_acme',
    category: 'computer_action',
    riskLevel: 'critical',
    planTierRequired: 'enterprise',
    inputSchema: { type: 'object', properties: { target: { type: 'string' }, action: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { success: { type: 'boolean' } } },
    creditCost: 50,
    deterministic: false,
    explainabilityRequired: true,
    permissions: ['computer.action', 'wallet.deduct'],
    compatibleModels: ['gpt-4o'],
    dependencies: [],
    platforms: ['desktop'],
    tags: ['computer-action', 'automation'],
    modelsUsed: ['gpt-4o'],
    lifecycleStatus: 'review',
    certified: false,
    featured: false,
    trending: false,
    installCount: 45,
    rating: 3.9,
    reviewCount: 6,
  },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_featured_q2',
    name: 'Q2 Featured Apps',
    type: 'featured',
    resourceIds: ['app_invoice_ai', 'app_supply_chain_ai', 'app_compliance_guard'],
    startDate: '2025-04-01T00:00:00Z',
    endDate: '2025-06-30T23:59:59Z',
    active: true,
  },
  {
    id: 'camp_editors_picks',
    name: "Editor's Picks — June 2025",
    type: 'editors_pick',
    resourceIds: ['app_invoice_ai', 'app_customer_support_ai'],
    startDate: '2025-06-01T00:00:00Z',
    endDate: '2025-06-30T23:59:59Z',
    active: true,
  },
];

export const SEED_DEALS: Deal[] = [
  {
    id: 'deal_q2_finance',
    title: '20% off Finance Apps',
    description: 'Save 20% on Invoice AI and finance automation packs this quarter.',
    discountPercent: 20,
    appIds: ['app_invoice_ai'],
    validUntil: '2025-06-30T23:59:59Z',
    code: 'FINANCE20',
  },
  {
    id: 'deal_support_bundle',
    title: 'Support AI Bundle',
    description: 'Get Customer Support AI Pro free for 3 months with Enterprise plan.',
    discountPercent: 100,
    appIds: ['app_customer_support_ai'],
    validUntil: '2025-07-31T23:59:59Z',
  },
];

export const SEED_REVIEWS: Omit<Review, 'id' | 'createdAt'>[] = [
  {
    resourceType: 'app',
    resourceId: 'app_invoice_ai',
    userId: 'user_demo',
    rating: 5,
    title: 'Transformed our AP workflow',
    comment: 'Invoice AI cut our processing time by 70%. The extraction accuracy is excellent.',
    verifiedUsage: true,
  },
  {
    resourceType: 'app',
    resourceId: 'app_invoice_ai',
    userId: 'user_cfo',
    rating: 4,
    title: 'Great but needs more ERP connectors',
    comment: 'Solid product. Would love native SAP integration.',
    verifiedUsage: true,
  },
  {
    resourceType: 'app',
    resourceId: 'app_supply_chain_ai',
    userId: 'user_procurement',
    rating: 5,
    title: 'Best procurement AI we have used',
    comment: 'Explainable scoring helps our team trust automated award decisions.',
    verifiedUsage: true,
  },
  {
    resourceType: 'skill',
    resourceId: 'skill_invoice_extract',
    userId: 'user_dev',
    rating: 5,
    comment: 'Clean API, reliable extraction. Used in 3 of our agents.',
    verifiedUsage: true,
  },
];

/** Map seed slugs to stable IDs used after registration */
export const SEED_APP_IDS: Record<string, string> = {
  'invoice-ai': 'app_invoice_ai',
  'supply-chain-ai': 'app_supply_chain_ai',
  'customer-support-ai': 'app_customer_support_ai',
  'compliance-ai': 'app_compliance_ai',
  'hr-ai': 'app_hr_ai',
  'compliance-guard': 'app_compliance_guard',
  'agent-toolkit-oss': 'app_agent_toolkit_oss',
  'legal-contract-ai': 'app_legal_contract_ai',
  'marketing-insights-ai': 'app_marketing_insights_ai',
  'vision-qa-inspector': 'app_vision_qa_inspector',
  'sales-ai': 'app_sales_ai',
  'sales-copilot': 'app_sales_ai',
  'knowledge-pipeline-pack': 'app_knowledge_pipeline_pack',
  'content-ai': 'app_content_ai',
  'iot-anomaly-detector': 'app_iot_anomaly_detector',
};

export const SEED_COLLECTIONS: Collection[] = [
  {
    id: 'col_finance_starter',
    name: 'Finance Starter Pack',
    slug: 'finance-starter',
    description: 'Invoice AI + compliance skills for finance teams.',
    appIds: ['app_invoice_ai', 'app_compliance_guard'],
    skillIds: ['skill_invoice_extract', 'skill_invoice_decision'],
    featured: true,
  },
  {
    id: 'col_agent_builder',
    name: 'Agent Builder Collection',
    slug: 'agent-builder',
    description: 'Skills and packs for building production AI agents.',
    appIds: ['app_agent_toolkit_oss', 'app_knowledge_pipeline_pack'],
    skillIds: ['skill_rag_retrieve', 'skill_generic_parse'],
    featured: true,
  },
];

export const SEED_INDUSTRY_PACKS: IndustryPack[] = [
  {
    id: 'pack_finance',
    name: 'Finance Industry Pack',
    industry: 'finance',
    description: 'Complete finance automation suite.',
    appIds: ['app_invoice_ai', 'app_compliance_guard'],
    skillIds: ['skill_invoice_extract', 'skill_compliance_check'],
  },
  {
    id: 'pack_supply_chain',
    name: 'Supply Chain Industry Pack',
    industry: 'supply_chain',
    description: 'Procurement and supplier evaluation tools.',
    appIds: ['app_supply_chain_ai'],
    skillIds: ['skill_offer_parse', 'skill_supplier_score'],
  },
  {
    id: 'pack_healthcare',
    name: 'Healthcare Compliance Pack',
    industry: 'healthcare',
    description: 'Compliance and document skills for healthcare.',
    appIds: ['app_compliance_guard'],
    skillIds: ['skill_compliance_check', 'skill_ocr_extract'],
  },
];

export const SEED_COUPONS: Coupon[] = [
  {
    id: 'coupon_welcome20',
    code: 'WELCOME20',
    discountPercent: 20,
    appIds: ['app_invoice_ai', 'app_hr_ai'],
    validUntil: '2025-12-31T23:59:59Z',
    active: true,
  },
];

export const SEED_BUNDLES: Bundle[] = [
  {
    id: 'bundle_support_sales',
    name: 'Support + Sales Bundle',
    description: 'Customer Support AI and Sales AI together.',
    appIds: ['app_customer_support_ai', 'app_sales_ai'],
    discountPercent: 15,
  },
];
