/** Sales AI agents for Agent Studio */
export const SALES_AI_AGENTS = [
  {
    name: 'Research Agent',
    description: 'Researches leads, companies, and decision makers for outreach',
    type: 'sales_research',
    agentType: 'Sales' as const,
    skillIds: ['skill_lead_score', 'skill_rag_retrieve'],
    inputSchema: { type: 'object', properties: { company: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { summary: { type: 'string' }, score: { type: 'number' } } },
    riskLevel: 'low' as const,
    status: 'active' as const,
  },
  {
    name: 'Email Agent',
    description: 'Generates personalized cold, follow-up, and intro emails',
    type: 'sales_email',
    agentType: 'Sales' as const,
    skillIds: ['skill_lead_score'],
    inputSchema: { type: 'object', properties: { leadId: { type: 'string' }, type: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { subject: { type: 'string' }, body: { type: 'string' } } },
    riskLevel: 'medium' as const,
    status: 'active' as const,
  },
  {
    name: 'Proposal Agent',
    description: 'Creates proposals, quotations, and RFP responses',
    type: 'sales_proposal',
    agentType: 'Sales' as const,
    skillIds: ['skill_rag_retrieve'],
    inputSchema: { type: 'object', properties: { requirements: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { title: { type: 'string' }, sections: { type: 'array' } } },
    riskLevel: 'medium' as const,
    status: 'active' as const,
  },
  {
    name: 'Meeting Agent',
    description: 'Prepares meeting briefs with company intel and strategy',
    type: 'sales_meeting',
    agentType: 'Sales' as const,
    skillIds: ['skill_rag_retrieve', 'skill_lead_score'],
    inputSchema: { type: 'object', properties: { company: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { agenda: { type: 'array' }, questions: { type: 'array' } } },
    riskLevel: 'low' as const,
    status: 'active' as const,
  },
  {
    name: 'Negotiation Agent',
    description: 'Handles objections and suggests negotiation strategies',
    type: 'sales_negotiation',
    agentType: 'Sales' as const,
    skillIds: ['skill_lead_score'],
    inputSchema: { type: 'object', properties: { objection: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { response: { type: 'string' }, strategy: { type: 'string' } } },
    riskLevel: 'high' as const,
    status: 'active' as const,
  },
  {
    name: 'CRM Agent',
    description: 'Syncs leads, contacts, and deals to CRM systems',
    type: 'sales_crm',
    agentType: 'Sales' as const,
    skillIds: ['skill_api_crm_sync'],
    inputSchema: { type: 'object', properties: { entityType: { type: 'string' }, entityId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { externalId: { type: 'string' } } },
    riskLevel: 'high' as const,
    status: 'active' as const,
  },
];
