/** Compliance AI agents for Agent Studio */
export const COMPLIANCE_AI_AGENTS = [
  {
    name: 'Compliance Copilot',
    description: 'AI compliance assistant — explain requirements, suggest remediation, generate policies',
    type: 'compliance_copilot',
    agentType: 'Compliance' as const,
    skillIds: ['skill_compliance_check', 'skill_policy_generate'],
    inputSchema: { type: 'object', properties: { message: { type: 'string' }, tenantId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { response: { type: 'string' }, citations: { type: 'array' } } },
    riskLevel: 'medium' as const,
    status: 'active' as const,
  },
  {
    name: 'Evidence Analyzer',
    description: 'Validate and analyze compliance evidence artifacts',
    type: 'compliance_evidence',
    agentType: 'Compliance' as const,
    skillIds: ['skill_compliance_check'],
    inputSchema: { type: 'object', properties: { evidenceId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { valid: { type: 'boolean' }, findings: { type: 'array' } } },
    riskLevel: 'low' as const,
    status: 'active' as const,
  },
  {
    name: 'Risk Analyst',
    description: 'Assess security, privacy, and AI risks with control mapping',
    type: 'compliance_risk',
    agentType: 'Compliance' as const,
    skillIds: ['skill_compliance_check'],
    inputSchema: { type: 'object', properties: { riskId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { score: { type: 'number' }, mitigations: { type: 'array' } } },
    riskLevel: 'high' as const,
    status: 'active' as const,
  },
  {
    name: 'Policy Generator',
    description: 'Generate policies from templates aligned to frameworks',
    type: 'compliance_policy',
    agentType: 'Compliance' as const,
    skillIds: ['skill_policy_generate'],
    inputSchema: { type: 'object', properties: { templateType: { type: 'string' }, frameworkCode: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { content: { type: 'string' } } },
    riskLevel: 'medium' as const,
    status: 'active' as const,
  },
  {
    name: 'Audit Prep Agent',
    description: 'Compile audit evidence packages and readiness reports',
    type: 'compliance_audit',
    agentType: 'Compliance' as const,
    skillIds: ['skill_compliance_check', 'skill_policy_generate'],
    inputSchema: { type: 'object', properties: { frameworkId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { packageId: { type: 'string' }, gaps: { type: 'array' } } },
    riskLevel: 'high' as const,
    status: 'active' as const,
  },
];
