import type { Agent } from '@ai-pass/agent-studio';

const SKILL = {
  ocr: 'skill_ocr_invoice',
  fraud: 'skill_fraud_score',
  compliance: 'skill_compliance_check',
  decision: 'skill_decision_engine',
  notify: 'skill_notify',
  rag: 'skill_rag_retrieval',
} as const;

/** Invoice AI Agent Studio agent definitions — routed via platform skill executor */
export const INVOICE_AI_AGENTS: Array<
  Omit<Agent, 'createdAt' | 'updatedAt' | 'currentVersion'> & { id: string }
> = [
  {
    id: 'agent_extraction',
    name: 'Extraction Agent',
    description: 'OCR and field extraction from invoice documents',
    type: 'invoice_extraction',
    agentType: 'Document',
    skillIds: [SKILL.ocr],
    inputSchema: { type: 'object', properties: { fileName: { type: 'string' }, mimeType: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { fields: { type: 'object' }, amount: { type: 'number' } } },
    riskLevel: 'low',
    status: 'active',
  },
  {
    id: 'agent_validation',
    name: 'Validation Agent',
    description: 'Compliance checks, budget validation, required fields',
    type: 'invoice_validation',
    agentType: 'Compliance',
    skillIds: [SKILL.compliance, SKILL.decision],
    inputSchema: { type: 'object', properties: { invoiceId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { decision: { type: 'string' }, checks: { type: 'array' } } },
    riskLevel: 'medium',
    status: 'active',
  },
  {
    id: 'agent_fraud',
    name: 'Fraud Detection Agent',
    description: 'Duplicate detection, vendor risk, anomaly scoring',
    type: 'invoice_fraud',
    agentType: 'Finance',
    skillIds: [SKILL.fraud, SKILL.decision],
    inputSchema: { type: 'object', properties: { invoiceId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { alerts: { type: 'array' }, score: { type: 'number' } } },
    riskLevel: 'high',
    status: 'active',
  },
  {
    id: 'agent_compliance',
    name: 'Compliance Agent',
    description: 'Regulatory compliance, tax rules, industry-specific checks',
    type: 'invoice_compliance',
    agentType: 'Compliance',
    skillIds: [SKILL.compliance, SKILL.rag],
    inputSchema: { type: 'object', properties: { invoiceId: { type: 'string' }, packId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { compliant: { type: 'boolean' }, citations: { type: 'array' } } },
    riskLevel: 'high',
    status: 'active',
  },
  {
    id: 'agent_approval',
    name: 'Approval Agent',
    description: 'Approval matrix routing and escalation',
    type: 'invoice_approval',
    agentType: 'Workflow',
    skillIds: [SKILL.decision, SKILL.notify],
    inputSchema: { type: 'object', properties: { invoiceId: { type: 'string' }, amount: { type: 'number' } } },
    outputSchema: { type: 'object', properties: { approvers: { type: 'array' } } },
    riskLevel: 'medium',
    status: 'active',
  },
  {
    id: 'agent_audit',
    name: 'Audit Agent',
    description: 'Audit trail export and decision artifact logging',
    type: 'invoice_audit',
    agentType: 'Compliance',
    skillIds: [SKILL.notify],
    inputSchema: { type: 'object', properties: { entityId: { type: 'string' }, action: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { auditLogId: { type: 'string' } } },
    riskLevel: 'low',
    status: 'active',
  },
  {
    id: 'agent_payment',
    name: 'Payment Agent',
    description: 'Payment scheduling and ERP synchronization',
    type: 'invoice_payment',
    agentType: 'Finance',
    skillIds: [SKILL.decision, SKILL.notify],
    inputSchema: { type: 'object', properties: { invoiceId: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { scheduledDate: { type: 'string' }, erpRef: { type: 'string' } } },
    riskLevel: 'high',
    status: 'active',
  },
];

export const INVOICE_AGENT_IDS = {
  extraction: 'agent_extraction',
  validation: 'agent_validation',
  fraud: 'agent_fraud',
  compliance: 'agent_compliance',
  approval: 'agent_approval',
  audit: 'agent_audit',
  payment: 'agent_payment',
} as const;
