import type {
  Approval,
  AuditLog,
  FraudAlert,
  Invoice,
  InvoiceAutomationPack,
  InvoiceWorkflow,
  ValidationResult,
  Vendor,
} from '@ai-pass/shared/invoice-ai';

const TENANT = 'tenant_acme';

export const DEMO_VENDORS: Vendor[] = [
  {
    id: 'vnd_001',
    tenantId: TENANT,
    name: 'Acme Supplies GmbH',
    taxId: 'DE123456789',
    email: 'billing@acme-supplies.de',
    country: 'DE',
    riskScore: 12,
    status: 'active',
    totalSpend: 48200,
    invoiceCount: 34,
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'vnd_002',
    tenantId: TENANT,
    name: 'CloudHost Pro',
    taxId: 'US987654321',
    email: 'invoices@cloudhost.pro',
    country: 'US',
    riskScore: 8,
    status: 'active',
    totalSpend: 128400,
    invoiceCount: 12,
    createdAt: '2024-11-02T08:00:00Z',
  },
  {
    id: 'vnd_003',
    tenantId: TENANT,
    name: 'MediCare Billing AG',
    taxId: 'CH556677889',
    email: 'claims@medicare-billing.ch',
    country: 'CH',
    riskScore: 45,
    status: 'review',
    totalSpend: 22100,
    invoiceCount: 8,
    createdAt: '2025-03-10T14:00:00Z',
  },
  {
    id: 'vnd_004',
    tenantId: TENANT,
    name: 'Rapid Logistics Ltd',
    taxId: 'GB112233445',
    email: 'ap@rapidlogistics.co.uk',
    country: 'GB',
    riskScore: 72,
    status: 'blocked',
    totalSpend: 8900,
    invoiceCount: 3,
    createdAt: '2025-05-01T09:00:00Z',
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'inv_001',
    tenantId: TENANT,
    invoiceNumber: 'INV-2026-0142',
    vendorId: 'vnd_001',
    vendorName: 'Acme Supplies GmbH',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'pending_approval',
    amount: 4250.0,
    currency: 'EUR',
    taxAmount: 807.5,
    dueDate: '2026-07-15',
    items: [
      { id: 'li_1', description: 'Office supplies Q2', quantity: 1, unitPrice: 3442.5, total: 3442.5 },
      { id: 'li_2', description: 'Shipping', quantity: 1, unitPrice: 0, total: 0 },
    ],
    extractedFields: {
      invoice_number: { value: 'INV-2026-0142', confidence: 0.97 },
      vendor: { value: 'Acme Supplies GmbH', confidence: 0.95 },
      total: { value: 4250, confidence: 0.93 },
    },
    decision: 'NEEDS_INFO',
    department: 'Operations',
    uploadedAt: '2026-06-28T09:15:00Z',
    processedAt: '2026-06-28T09:16:30Z',
  },
  {
    id: 'inv_002',
    tenantId: TENANT,
    invoiceNumber: 'CH-88421',
    vendorId: 'vnd_002',
    vendorName: 'CloudHost Pro',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'approved',
    amount: 12800.0,
    currency: 'USD',
    taxAmount: 0,
    dueDate: '2026-07-01',
    items: [
      { id: 'li_3', description: 'Enterprise hosting — June', quantity: 1, unitPrice: 12800, total: 12800 },
    ],
    extractedFields: {
      invoice_number: { value: 'CH-88421', confidence: 0.99 },
      vendor: { value: 'CloudHost Pro', confidence: 0.98 },
      total: { value: 12800, confidence: 0.99 },
    },
    decision: 'PASS',
    department: 'IT',
    uploadedAt: '2026-06-27T14:30:00Z',
    processedAt: '2026-06-27T14:31:00Z',
  },
  {
    id: 'inv_003',
    tenantId: TENANT,
    invoiceNumber: 'MC-2026-0891',
    vendorId: 'vnd_003',
    vendorName: 'MediCare Billing AG',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'flagged',
    amount: 18750.0,
    currency: 'CHF',
    taxAmount: 1436.25,
    dueDate: '2026-07-20',
    items: [
      { id: 'li_4', description: 'Medical claims batch #891', quantity: 1, unitPrice: 17313.75, total: 17313.75 },
    ],
    extractedFields: {
      invoice_number: { value: 'MC-2026-0891', confidence: 0.91 },
      vendor: { value: 'MediCare Billing AG', confidence: 0.88 },
      total: { value: 18750, confidence: 0.85 },
    },
    decision: 'NEEDS_INFO',
    department: 'Healthcare',
    uploadedAt: '2026-06-29T08:00:00Z',
    processedAt: '2026-06-29T08:02:15Z',
  },
  {
    id: 'inv_004',
    tenantId: TENANT,
    invoiceNumber: 'RL-99001',
    vendorId: 'vnd_004',
    vendorName: 'Rapid Logistics Ltd',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'rejected',
    amount: 3200.0,
    currency: 'GBP',
    items: [
      { id: 'li_5', description: 'Freight services', quantity: 1, unitPrice: 3200, total: 3200 },
    ],
    extractedFields: {
      invoice_number: { value: 'RL-99001', confidence: 0.94 },
      vendor: { value: 'Rapid Logistics Ltd', confidence: 0.96 },
      total: { value: 3200, confidence: 0.92 },
    },
    decision: 'FAIL',
    department: 'Logistics',
    uploadedAt: '2026-06-25T11:00:00Z',
    processedAt: '2026-06-25T11:01:00Z',
  },
  {
    id: 'inv_005',
    tenantId: TENANT,
    invoiceNumber: 'INV-2026-0143',
    vendorId: 'vnd_001',
    vendorName: 'Acme Supplies GmbH',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'validated',
    amount: 890.5,
    currency: 'EUR',
    taxAmount: 169.2,
    dueDate: '2026-07-10',
    items: [
      { id: 'li_6', description: 'Printer cartridges', quantity: 10, unitPrice: 72.13, total: 721.3 },
    ],
    extractedFields: {
      invoice_number: { value: 'INV-2026-0143', confidence: 0.98 },
      vendor: { value: 'Acme Supplies GmbH', confidence: 0.97 },
      total: { value: 890.5, confidence: 0.96 },
    },
    decision: 'PASS',
    department: 'Operations',
    uploadedAt: '2026-06-29T10:30:00Z',
    processedAt: '2026-06-29T10:31:00Z',
  },
];

export const DEMO_FRAUD_ALERTS: FraudAlert[] = [
  {
    id: 'fraud_001',
    invoiceId: 'inv_003',
    tenantId: TENANT,
    type: 'vendor_risk',
    severity: 'high',
    title: 'Elevated vendor risk score',
    description: 'MediCare Billing AG has risk score 45 — above threshold of 40.',
    status: 'open',
    score: 0.78,
    createdAt: '2026-06-29T08:02:20Z',
  },
  {
    id: 'fraud_002',
    invoiceId: 'inv_003',
    tenantId: TENANT,
    type: 'duplicate',
    severity: 'medium',
    title: 'Potential duplicate invoice',
    description: 'Similar amount and vendor detected within 30-day window.',
    status: 'investigating',
    score: 0.62,
    createdAt: '2026-06-29T08:02:25Z',
  },
  {
    id: 'fraud_003',
    invoiceId: 'inv_004',
    tenantId: TENANT,
    type: 'vendor_risk',
    severity: 'critical',
    title: 'Blocked vendor invoice',
    description: 'Rapid Logistics Ltd is on vendor blacklist.',
    status: 'resolved',
    score: 0.95,
    createdAt: '2026-06-25T11:01:05Z',
    resolvedAt: '2026-06-25T14:00:00Z',
  },
];

export const DEMO_APPROVALS: Approval[] = [
  {
    id: 'appr_001',
    invoiceId: 'inv_001',
    tenantId: TENANT,
    approverId: 'user_finance_mgr',
    approverName: 'Sarah Chen',
    level: 1,
    status: 'pending',
    requestedAt: '2026-06-28T09:17:00Z',
  },
  {
    id: 'appr_002',
    invoiceId: 'inv_002',
    tenantId: TENANT,
    approverId: 'user_cfo',
    approverName: 'David Park',
    level: 1,
    status: 'approved',
    comment: 'Within IT budget allocation',
    requestedAt: '2026-06-27T14:32:00Z',
    decidedAt: '2026-06-27T16:00:00Z',
  },
];

export const DEMO_WORKFLOWS: InvoiceWorkflow[] = [
  {
    id: 'wf_default',
    tenantId: TENANT,
    name: 'Standard Invoice Processing',
    description: 'Extract → Validate → Fraud → Approve → Payment',
    mode: 'semi_automated',
    steps: [
      { id: 's1', type: 'trigger', label: 'Invoice Uploaded', next: ['s2'] },
      { id: 's2', type: 'extract', label: 'OCR Extraction', agentId: 'agent_extraction', next: ['s3'] },
      { id: 's3', type: 'validate', label: 'Compliance Validation', agentId: 'agent_validation', next: ['s4'] },
      { id: 's4', type: 'fraud', label: 'Fraud Detection', agentId: 'agent_fraud', next: ['s5'] },
      { id: 's5', type: 'approve', label: 'Approval Routing', agentId: 'agent_approval', next: ['s6'] },
      { id: 's6', type: 'payment', label: 'Schedule Payment', agentId: 'agent_payment' },
    ],
    isActive: true,
    version: 3,
    createdAt: '2025-06-01T00:00:00Z',
    updatedAt: '2026-06-15T12:00:00Z',
  },
  {
    id: 'wf_healthcare',
    tenantId: TENANT,
    name: 'Healthcare Claims Workflow',
    description: 'Insurance pack — coverage check + medical classification',
    mode: 'semi_automated',
    steps: [
      { id: 'h1', type: 'trigger', label: 'Claim Invoice Received', next: ['h2'] },
      { id: 'h2', type: 'extract', label: 'Medical Field Extraction', agentId: 'agent_extraction', next: ['h3'] },
      { id: 'h3', type: 'validate', label: 'Coverage Verification', agentId: 'agent_compliance', next: ['h4'] },
      { id: 'h4', type: 'fraud', label: 'Claims Fraud Check', agentId: 'agent_fraud', next: ['h5'] },
      { id: 'h5', type: 'approve', label: 'Claims Approval', agentId: 'agent_approval' },
    ],
    isActive: false,
    version: 1,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
];

export const DEMO_VALIDATIONS: ValidationResult[] = [
  {
    id: 'val_001',
    invoiceId: 'inv_001',
    passed: false,
    decision: 'NEEDS_INFO',
    checks: [
      { rule: 'required_fields', passed: true, message: 'All required fields present', severity: 'info' },
      { rule: 'budget_check', passed: false, message: 'Exceeds department budget by 12%', severity: 'warning' },
      { rule: 'tax_validation', passed: true, message: 'VAT rate valid for DE', severity: 'info' },
    ],
    confidence: 0.87,
    validatedAt: '2026-06-28T09:16:30Z',
  },
  {
    id: 'val_002',
    invoiceId: 'inv_002',
    passed: true,
    decision: 'PASS',
    checks: [
      { rule: 'required_fields', passed: true, message: 'All required fields present', severity: 'info' },
      { rule: 'budget_check', passed: true, message: 'Within IT budget', severity: 'info' },
      { rule: 'vendor_status', passed: true, message: 'Vendor active', severity: 'info' },
    ],
    confidence: 0.96,
    validatedAt: '2026-06-27T14:31:00Z',
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_001',
    tenantId: TENANT,
    entityType: 'invoice',
    entityId: 'inv_001',
    action: 'invoice.uploaded',
    actorId: 'demo-user',
    actorName: 'Jordan Lee',
    details: { fileName: 'acme-q2-invoice.pdf' },
    creditsUsed: 15,
    timestamp: '2026-06-28T09:15:00Z',
  },
  {
    id: 'aud_002',
    tenantId: TENANT,
    entityType: 'approval',
    entityId: 'appr_002',
    action: 'invoice.approved',
    actorId: 'user_cfo',
    actorName: 'David Park',
    details: { invoiceId: 'inv_002', amount: 12800 },
    timestamp: '2026-06-27T16:00:00Z',
  },
];

export const DEMO_AUTOMATION_PACKS: InvoiceAutomationPack[] = [
  {
    id: 'pack_insurance',
    industry: 'insurance',
    name: 'Insurance Claims Invoice Pack',
    description: 'Claims validation, medical verification, coverage cross-check, fraud scoring',
    triggers: ['invoice.uploaded', 'claim.submitted'],
    skills: ['CoverageVerificationSkill', 'MedicalClassificationSkill', 'ClaimsApprovalDecisionSkill'],
    approvalMatrix: { under_1000: 'auto', over_1000: 'manager' },
    tier: 'enterprise',
    pricingModel: 'subscription',
  },
  {
    id: 'pack_healthcare',
    industry: 'healthcare',
    name: 'Healthcare & Medical Billing Pack',
    description: 'Reimbursement validation, treatment codes, duplicate detection',
    triggers: ['invoice.uploaded', 'claim.received'],
    skills: ['TreatmentCodeVerificationSkill', 'CoverageValidationSkill', 'DuplicateDetectionSkill'],
    approvalMatrix: { all: 'clinical_review' },
    tier: 'enterprise',
    pricingModel: 'subscription',
  },
  {
    id: 'pack_financial_services',
    industry: 'financial_services',
    name: 'Financial Services Pack',
    description: 'Multi-entity allocation, tax classification, AML anomaly detection',
    triggers: ['invoice.uploaded', 'erp.sync'],
    skills: ['TaxClassificationSkill', 'AMLAnomalySkill', 'CostAllocationSkill'],
    approvalMatrix: { over_5000: 'compliance' },
    tier: 'enterprise',
    pricingModel: 'per_run',
  },
  {
    id: 'pack_public_sector',
    industry: 'public_sector',
    name: 'Public Sector Procurement Pack',
    description: 'Tender compliance, documentation validation, budget authorization',
    triggers: ['invoice.received', 'tender.closed'],
    skills: ['BudgetValidationSkill', 'ComplianceCheckSkill', 'AuditExportSkill'],
    approvalMatrix: { all: 'multi_department' },
    tier: 'professional',
    pricingModel: 'subscription',
  },
];

export const DEMO_TENANT_ID = TENANT;

export function getDashboardStats(invoices: Invoice[], fraudAlerts: FraudAlert[], vendors: Vendor[]) {
  const today = new Date().toISOString().slice(0, 10);
  const todayProcessed = invoices.filter((i) => i.processedAt?.startsWith(today)).length;
  const awaitingApproval = invoices.filter((i) => i.status === 'pending_approval').length;
  const openFraud = fraudAlerts.filter((a) => a.status === 'open' || a.status === 'investigating').length;
  const monthlySpend = invoices
    .filter((i) => i.status === 'approved' || i.status === 'paid')
    .reduce((sum, i) => sum + i.amount, 0);
  const approved = invoices.filter((i) => i.status === 'approved' || i.status === 'paid').length;
  const total = invoices.length;

  return {
    todayProcessed,
    awaitingApproval,
    fraudAlerts: openFraud,
    monthlySpend,
    vendorCount: vendors.length,
    approvalRate: total > 0 ? Math.round((approved / total) * 100) : 0,
  };
}
