import type {
  AISystem,
  Approval,
  ComplianceMapping,
  GovernancePolicy,
  MonitoringEvent,
  Risk,
} from '@ai-pass/shared';

const NOW = '2026-06-28T10:00:00Z';

export const SEED_SYSTEMS: AISystem[] = [
  {
    id: 'ais_inv_agent',
    name: 'Invoice Validation Agent',
    type: 'agent',
    ownerId: 'user_finance_lead',
    department: 'Finance',
    businessPurpose: 'Automated invoice validation and fraud detection',
    provider: 'Anthropic',
    version: '2.1.0',
    riskClassification: 'medium',
    complianceStatus: 'compliant',
    certificationStatus: 'gold',
    certificationId: 'cert_inv_001',
    deploymentEnvironment: 'production',
    monitoringStatus: 'active',
    connectedWorkflows: ['wf_invoice_validation'],
    trustScore: 91,
    lifecycleStage: 'monitoring',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'ais_support_bot',
    name: 'Customer Support Bot',
    type: 'agent',
    ownerId: 'user_support_mgr',
    department: 'Customer Success',
    businessPurpose: 'Multi-language customer support automation',
    provider: 'OpenAI',
    version: '3.0.2',
    riskClassification: 'high',
    complianceStatus: 'conditional',
    certificationStatus: 'silver',
    deploymentEnvironment: 'production',
    monitoringStatus: 'active',
    connectedWorkflows: ['wf_support_triage'],
    trustScore: 78,
    lifecycleStage: 'monitoring',
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'ais_supply_workflow',
    name: 'Supplier Evaluation Workflow',
    type: 'workflow',
    ownerId: 'user_procurement',
    department: 'Procurement',
    businessPurpose: 'Automated supplier offer scoring and ranking',
    provider: 'AI Pass',
    version: '1.4.0',
    riskClassification: 'medium',
    complianceStatus: 'compliant',
    certificationStatus: 'gold',
    deploymentEnvironment: 'production',
    monitoringStatus: 'active',
    connectedWorkflows: ['wf_supplier_recommendation'],
    trustScore: 88,
    lifecycleStage: 'monitoring',
    createdAt: '2026-02-10T11:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'ais_gpt4_router',
    name: 'GPT-4 Enterprise Router',
    type: 'model',
    ownerId: 'user_platform_admin',
    department: 'IT',
    businessPurpose: 'Central model routing for enterprise workloads',
    provider: 'OpenAI',
    version: 'gpt-4.1',
    riskClassification: 'high',
    complianceStatus: 'pending_review',
    deploymentEnvironment: 'production',
    monitoringStatus: 'degraded',
    connectedWorkflows: [],
    trustScore: 72,
    lifecycleStage: 'policy_validation',
    createdAt: '2026-03-01T14:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'ais_hr_app',
    name: 'HR Onboarding App',
    type: 'marketplace_app',
    ownerId: 'user_hr_director',
    department: 'Human Resources',
    businessPurpose: 'Employee onboarding document processing',
    provider: 'AI Pass Marketplace',
    version: '1.0.0',
    riskClassification: 'high',
    complianceStatus: 'non_compliant',
    deploymentEnvironment: 'staging',
    monitoringStatus: 'paused',
    connectedWorkflows: [],
    lifecycleStage: 'approval',
    createdAt: '2026-04-05T10:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'ais_knowledge_rag',
    name: 'Compliance Knowledge RAG',
    type: 'application',
    ownerId: 'user_compliance',
    department: 'Legal & Compliance',
    businessPurpose: 'Regulatory document retrieval and Q&A',
    provider: 'Anthropic',
    version: '2.0.1',
    riskClassification: 'critical',
    complianceStatus: 'compliant',
    certificationStatus: 'platinum',
    deploymentEnvironment: 'production',
    monitoringStatus: 'active',
    connectedWorkflows: ['wf_knowledge_sync'],
    trustScore: 95,
    lifecycleStage: 'monitoring',
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'ais_custom_analytics',
    name: 'Custom Analytics Pipeline',
    type: 'custom',
    ownerId: 'user_data_science',
    department: 'Data Science',
    businessPurpose: 'Internal ML pipeline for sales forecasting',
    provider: 'Private LLM',
    version: '0.9.3',
    riskClassification: 'medium',
    complianceStatus: 'pending_review',
    deploymentEnvironment: 'development',
    monitoringStatus: 'active',
    connectedWorkflows: ['wf_analysis_auto_run'],
    lifecycleStage: 'risk_assessment',
    createdAt: '2026-05-12T16:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'ais_erp_integration',
    name: 'ERP Sync Integration',
    type: 'integration',
    ownerId: 'user_it_ops',
    department: 'IT Operations',
    businessPurpose: 'Bidirectional ERP data synchronization',
    provider: 'AI Pass',
    version: '1.2.0',
    riskClassification: 'low',
    complianceStatus: 'compliant',
    certificationStatus: 'bronze',
    deploymentEnvironment: 'production',
    monitoringStatus: 'active',
    connectedWorkflows: ['wf_invoice_validation'],
    trustScore: 82,
    lifecycleStage: 'monitoring',
    createdAt: '2026-03-20T12:00:00Z',
    updatedAt: NOW,
  },
];

export const SEED_POLICIES: GovernancePolicy[] = [
  {
    id: 'pol_model_allowlist',
    name: 'Approved Model Allowlist',
    version: '2.0.0',
    category: 'model_selection',
    description: 'Only approved models may be used in production workloads',
    rules: [
      { id: 'r_allowed', type: 'allowed_models', condition: { models: ['claude-sonnet-4', 'gpt-4.1', 'gemini-2.5-pro'] }, action: 'block', severity: 'critical' },
    ],
    applicableSystemTypes: ['agent', 'workflow', 'model', 'application'],
    frameworks: ['ISO_42001', 'SOC2'],
    status: 'published',
    active: true,
    publishedAt: '2026-01-01T00:00:00Z',
    createdBy: 'user_compliance',
    createdAt: '2025-12-01T00:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'pol_pii_protection',
    name: 'PII Protection Policy',
    version: '1.3.0',
    category: 'data',
    description: 'Mandatory PII masking before external model calls',
    rules: [
      { id: 'r_pii', type: 'pii_masking', condition: {}, action: 'block', severity: 'critical' },
    ],
    applicableSystemTypes: ['agent', 'workflow', 'application', 'marketplace_app'],
    frameworks: ['GDPR', 'ISO_27001'],
    status: 'published',
    active: true,
    publishedAt: '2026-01-15T00:00:00Z',
    createdBy: 'user_compliance',
    createdAt: '2025-11-01T00:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'pol_high_risk_approval',
    name: 'High-Risk Human Approval',
    version: '1.0.0',
    category: 'approval',
    description: 'High and critical risk actions require human approval',
    rules: [
      { id: 'r_hra', type: 'human_approval', condition: {}, action: 'require_approval', severity: 'high' },
    ],
    applicableSystemTypes: ['agent', 'workflow', 'custom'],
    frameworks: ['ISO_42001', 'DORA'],
    status: 'published',
    active: true,
    publishedAt: '2026-02-01T00:00:00Z',
    createdBy: 'user_compliance',
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'pol_prompt_restrictions',
    name: 'Prompt Content Restrictions',
    version: '1.1.0',
    category: 'prompt',
    description: 'Block prompts containing sensitive keywords',
    rules: [
      { id: 'r_prompt', type: 'prohibited_prompt', condition: { pattern: 'bypass security' }, action: 'block', severity: 'critical' },
      { id: 'r_cite', type: 'mandatory_citation', condition: {}, action: 'escalate', severity: 'medium' },
    ],
    applicableSystemTypes: ['agent', 'application'],
    frameworks: ['internal', 'SOC2'],
    status: 'published',
    active: true,
    publishedAt: '2026-03-01T00:00:00Z',
    createdBy: 'user_security',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'pol_confidence_threshold',
    name: 'Minimum Confidence Threshold',
    version: '1.0.0',
    category: 'ai_usage',
    description: 'Outputs below confidence threshold require human review',
    rules: [
      { id: 'r_conf', type: 'confidence_threshold', condition: { min: 0.75 }, action: 'require_approval', severity: 'medium' },
    ],
    applicableSystemTypes: ['agent', 'workflow'],
    frameworks: ['ISO_42001'],
    status: 'published',
    active: true,
    publishedAt: '2026-04-01T00:00:00Z',
    createdBy: 'user_compliance',
    createdAt: '2026-03-20T00:00:00Z',
    updatedAt: NOW,
  },
];

export const SEED_RISKS: Risk[] = [
  {
    id: 'rsk_hallucination_support',
    systemId: 'ais_support_bot',
    category: 'hallucination',
    title: 'Support bot factual accuracy',
    description: 'Bot may generate incorrect product information for new SKUs',
    impact: 'high',
    likelihood: 'medium',
    score: 6,
    ownerId: 'user_support_mgr',
    mitigationPlan: 'Enable citation requirements and knowledge base grounding',
    reviewSchedule: '2026-07-15T00:00:00Z',
    status: 'open',
    frameworks: ['ISO_42001'],
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'rsk_privacy_hr',
    systemId: 'ais_hr_app',
    category: 'privacy',
    title: 'HR PII exposure risk',
    description: 'Onboarding documents contain sensitive employee PII',
    impact: 'critical',
    likelihood: 'medium',
    score: 8,
    ownerId: 'user_hr_director',
    mitigationPlan: 'Implement PII masking and data residency controls',
    reviewSchedule: '2026-07-01T00:00:00Z',
    status: 'open',
    frameworks: ['GDPR', 'ISO_27001'],
    createdAt: '2026-05-10T00:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'rsk_provider_gpt4',
    systemId: 'ais_gpt4_router',
    category: 'provider',
    title: 'Provider dependency — OpenAI',
    description: 'Single-provider dependency for critical routing layer',
    impact: 'high',
    likelihood: 'low',
    score: 3,
    ownerId: 'user_platform_admin',
    mitigationPlan: 'Add fallback routing to Anthropic and private LLM',
    reviewSchedule: '2026-08-01T00:00:00Z',
    status: 'in_review',
    frameworks: ['DORA', 'NIS2'],
    createdAt: '2026-04-20T00:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'rsk_drift_analytics',
    systemId: 'ais_custom_analytics',
    category: 'model_drift',
    title: 'Sales forecast model drift',
    description: 'Model accuracy degrading on Q2 seasonal patterns',
    impact: 'medium',
    likelihood: 'high',
    score: 6,
    ownerId: 'user_data_science',
    mitigationPlan: 'Retrain with Q2 data and enable drift monitoring',
    reviewSchedule: '2026-07-20T00:00:00Z',
    status: 'open',
    frameworks: ['internal'],
    createdAt: '2026-06-15T00:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'rsk_bias_hr',
    systemId: 'ais_hr_app',
    category: 'bias',
    title: 'Onboarding bias in document screening',
    description: 'Potential demographic bias in automated document classification',
    impact: 'high',
    likelihood: 'low',
    score: 3,
    ownerId: 'user_hr_director',
    reviewSchedule: '2026-08-15T00:00:00Z',
    status: 'open',
    frameworks: ['ISO_42001', 'GDPR'],
    createdAt: '2026-05-20T00:00:00Z',
    updatedAt: NOW,
  },
  {
    id: 'rsk_security_rag',
    systemId: 'ais_knowledge_rag',
    category: 'security',
    title: 'Unauthorized access to regulatory docs',
    description: 'Risk of cross-tenant data leakage in RAG retrieval',
    impact: 'critical',
    likelihood: 'low',
    score: 4,
    ownerId: 'user_compliance',
    mitigationPlan: 'Tenant isolation verified; quarterly penetration testing',
    reviewSchedule: '2026-09-01T00:00:00Z',
    status: 'mitigated',
    frameworks: ['ISO_27001', 'SOC2'],
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: NOW,
  },
];

export const SEED_APPROVALS: Approval[] = [
  {
    id: 'apr_hr_deploy',
    systemId: 'ais_hr_app',
    type: 'deployment',
    requestedBy: 'user_hr_director',
    assigneeId: 'user_compliance',
    reason: 'HR Onboarding App deployment to production — pending PII controls',
    status: 'pending',
    priority: 'high',
    createdAt: '2026-06-27T14:00:00Z',
  },
  {
    id: 'apr_gpt4_prod',
    systemId: 'ais_gpt4_router',
    type: 'manual',
    requestedBy: 'user_platform_admin',
    assigneeId: 'user_security',
    reason: 'Approve GPT-4 router for production traffic after policy review',
    status: 'pending',
    priority: 'high',
    createdAt: '2026-06-26T10:00:00Z',
  },
  {
    id: 'apr_analytics_exception',
    systemId: 'ais_custom_analytics',
    policyId: 'pol_model_allowlist',
    type: 'exception',
    requestedBy: 'user_data_science',
    reason: 'Exception: use private LLM not on allowlist for internal analytics',
    status: 'pending',
    priority: 'medium',
    createdAt: '2026-06-25T16:00:00Z',
  },
  {
    id: 'apr_support_recert',
    systemId: 'ais_support_bot',
    type: 'manual',
    requestedBy: 'user_support_mgr',
    assigneeId: 'user_compliance',
    reason: 'Re-certification required after hallucination incident',
    status: 'escalated',
    priority: 'critical',
    escalatedTo: 'user_ciso',
    createdAt: '2026-06-24T09:00:00Z',
  },
];

export const SEED_MONITORING: MonitoringEvent[] = [
  {
    id: 'mon_hallucination_001',
    systemId: 'ais_support_bot',
    type: 'hallucination',
    severity: 'high',
    title: 'Factual error in product response',
    details: { query: 'warranty period SKU-9921', confidence: 0.62 },
    recommendation: 'Enable mandatory citation and retrain on product catalog',
    acknowledged: false,
    timestamp: '2026-06-28T08:30:00Z',
  },
  {
    id: 'mon_drift_001',
    systemId: 'ais_custom_analytics',
    type: 'drift',
    severity: 'medium',
    title: 'Forecast accuracy dropped 12%',
    details: { metric: 'mape', previousValue: 0.08, currentValue: 0.20 },
    recommendation: 'Trigger model retraining workflow',
    acknowledged: false,
    timestamp: '2026-06-27T22:00:00Z',
  },
  {
    id: 'mon_policy_001',
    systemId: 'ais_hr_app',
    type: 'policy_violation',
    severity: 'critical',
    title: 'PII sent unmasked to external model',
    details: { policyId: 'pol_pii_protection', field: 'ssn' },
    recommendation: 'Block deployment until PII masking is implemented',
    acknowledged: false,
    timestamp: '2026-06-27T15:45:00Z',
  },
  {
    id: 'mon_provider_001',
    systemId: 'ais_gpt4_router',
    type: 'provider_change',
    severity: 'medium',
    title: 'OpenAI API version updated',
    details: { from: '2024-11', to: '2025-03' },
    recommendation: 'Run regression validation suite',
    acknowledged: true,
    timestamp: '2026-06-26T11:00:00Z',
  },
  {
    id: 'mon_confidence_001',
    systemId: 'ais_inv_agent',
    type: 'confidence_low',
    severity: 'low',
    title: 'Low confidence on vendor match',
    details: { confidence: 0.71, threshold: 0.75 },
    recommendation: 'Route to human review queue',
    acknowledged: false,
    timestamp: '2026-06-28T06:00:00Z',
  },
];

export const SEED_COMPLIANCE_MAPPINGS: ComplianceMapping[] = [
  { id: 'map_iso42001_ai', framework: 'ISO_42001', controlId: '6.1.2', controlName: 'AI risk assessment', policyIds: ['pol_high_risk_approval'], systemIds: ['ais_support_bot', 'ais_knowledge_rag'], status: 'compliant', lastAssessedAt: NOW },
  { id: 'map_gdpr_pii', framework: 'GDPR', controlId: 'Art.32', controlName: 'Security of processing', policyIds: ['pol_pii_protection'], systemIds: ['ais_hr_app', 'ais_support_bot'], status: 'partial', lastAssessedAt: NOW },
  { id: 'map_soc2_access', framework: 'SOC2', controlId: 'CC6.1', controlName: 'Logical access controls', policyIds: ['pol_model_allowlist'], systemIds: ['ais_gpt4_router'], status: 'compliant', lastAssessedAt: NOW },
  { id: 'map_nis2_resilience', framework: 'NIS2', controlId: '21.2', controlName: 'Supply chain security', policyIds: ['pol_model_allowlist'], systemIds: ['ais_gpt4_router', 'ais_erp_integration'], status: 'partial', lastAssessedAt: NOW },
  { id: 'map_dora_ops', framework: 'DORA', controlId: '9.1', controlName: 'ICT risk management', policyIds: ['pol_high_risk_approval'], systemIds: ['ais_inv_agent'], status: 'compliant', lastAssessedAt: NOW },
  { id: 'map_internal_prompt', framework: 'internal', controlId: 'INT-003', controlName: 'Prompt safety standards', policyIds: ['pol_prompt_restrictions'], systemIds: ['ais_support_bot', 'ais_knowledge_rag'], status: 'compliant', lastAssessedAt: NOW },
];
